const kolaySorular = [
    { s: "Gündüzleri gökyüzünde parlayan sıcak yıldızın adı nedir?", c: "Güneş", yanlislar: ["Ay", "Mars", "Yıldız"] },
    { s: "Geceleri gökyüzünde parlayan beyaz küre nedir?", c: "Ay", yanlislar: ["Güneş", "Dünya", "Venüs"] },
    { s: "Üzerinde yaşadığımız mavi gezegenin adı nedir?", c: "Dünya", yanlislar: ["Mars", "Satürn", "Merkür"] },
    { s: "Kızıl Gezegen olarak bilinen komşu gezegenimiz hangisidir?", c: "Mars", yanlislar: ["Dünya", "Venüs", "Jüpiter"] },
    { s: "Güneş sistemindeki en büyük gezegen hangisidir?", c: "Jüpiter", yanlislar: ["Satürn", "Dünya", "Neptün"] },
    { s: "Etrafında kocaman halkaları olan dev gaz gezegeni hangisidir?", c: "Satürn", yanlislar: ["Uranüs", "Mars", "Merkür"] },
    { s: "Güneş'e en yakın olan birinci gezegen hangisidir?", c: "Merkür", yanlislar: ["Venüs", "Dünya", "Mars"] },
    { s: "Güneş sisteminin tam merkezinde ne bulunur?", c: "Güneş", yanlislar: ["Dünya", "Ay", "Jüpiter"] },
    { s: "Uzaya giden kişilere ne ad verilir?", c: "Astronot", yanlislar: ["Pilot", "Mühendis", "Kaptan"] },
    { s: "Uzaya gitmek için bindiğimiz dev taşıtın adı nedir?", c: "Roket", yanlislar: ["Uçak", "Tren", "Araba"] },
    { s: "Güneş sistemindeki gezegenler hangi gök cisminin etrafında döner?", c: "Güneş", yanlislar: ["Ay", "Dünya", "Mars"] },
    { s: "Dünya'nın etrafında dönen tek doğal uydu hangisidir?", c: "Ay", yanlislar: ["Güneş", "Phobos", "Titan"] },
    { s: "Geceleri gökyüzünde gördüğümüz minik ışıklı noktalara ne denir?", c: "Yıldız", yanlislar: ["Taş", "Kaya", "Bulut"] },
    { s: "Uranüs gezegeni uzayda hangi biçimde dönmesiyle ünlüdür?", c: "Yan yatmış bir varil gibi", yanlislar: ["Hızlı ve düz", "Ters yönde çok yavaş", "Hareketsiz durarak"] },
    { s: "Güneş sistemindeki en dıştaki buz devi gezegen hangisidir?", c: "Neptün", yanlislar: ["Satürn", "Venüs", "Merkür"] },
    { s: "Güneş sisteminde toplam kaç tane ana gezegen vardır?", c: "8", yanlislar: ["9", "7", "10"] },
    { s: "Hangi gezegen Güneş sisteminin en sıcak yüzeyine sahiptir?", c: "Venüs", yanlislar: ["Merkür", "Mars", "Dünya"] },
    { s: "Güneş ışınlarının Dünya'mıza ulaşması ortalama ne kadar sürer?", c: "8 dakika", yanlislar: ["1 saat", "30 saniye", "24 saat"] },
    { s: "Dünya'nın kendi ekseni etrafında bir tam tur dönmesi ne kadar sürer?", c: "24 saat (1 gün)", yanlislar: ["365 gün", "30 gün", "12 saat"] },
    { s: "Dünya'nın Güneş etrafında bir tam tur dönmesi ne kadar sürer?", c: "365 gün 6 saat (1 yıl)", yanlislar: ["24 saat", "1 ay", "10 yıl"] },
    { s: "Geceleri gökyüzünde gördüğümüz en parlak yıldız benzeri gezegen hangisidir?", c: "Venüs", yanlislar: ["Mars", "Satürn", "Jüpiter"] },
    { s: "Güneş sistemindeki en küçük gezegen hangisidir?", c: "Merkür", yanlislar: ["Mars", "Venüs", "Dünya"] },
    { s: "Hangi gezegen kendi etrafında saat yönünün tersine döner?", c: "Venüs", yanlislar: ["Dünya", "Mars", "Jüpiter"] },
    { s: "Güneş sistemindeki en yüksek dağ olan Olympus Mons hangi gezegendedir?", c: "Mars", yanlislar: ["Dünya", "Venüs", "Merkür"] },
    { s: "Hangi gezegenin yoğunluğu sudan küçüktür (suya atılsa yüzebilir)?", c: "Satürn", yanlislar: ["Jüpiter", "Dünya", "Neptün"] },
    { s: "Güneş'in ana maddesi ağırlıklı olarak hangi gazlardan oluşur?", c: "Hidrojen ve Helyum", yanlislar: ["Demir ve Nikel", "Oksijen ve Azot", "Karbondioksit"] },
    { s: "Dünyamıza en yakın olan yıldız hangisidir?", c: "Güneş", yanlislar: ["Sirius", "Alpha Centauri", "Polaris"] },
    { s: "Gök cisimlerini ve uzayı inceleyen bilim insanına ne denir?", c: "Gökbilimci (Astronom)", yanlislar: ["Jeolog", "Biyolog", "Meteorolog"] },
    { s: "Ay'ın evrelerinden yeni ay ile dolunay arasındaki döneme ne ad verilir?", c: "İlk dördün", yanlislar: ["Hilal", "Son dördün", "Tutulma"] },
    { s: "Güneş bir yıldız türü olarak hangi sınıfta yer alır?", c: "Sarı Cüce", yanlislar: ["Kırmızı Dev", "Nötron Yıldızı", "Beyaz Cüce"] },
    { s: "Ay'ın yüzeyindeki büyük çukurlara ne denir?", c: "Krater", yanlislar: ["Dağ", "Vadi", "Okyanus"] },
    { s: "Güneş sistemimiz hangi galaksinin içindedir?", c: "Samanyolu", yanlislar: ["Andromeda", "Sombrero", "Üçgen"] },
    { s: "Mars ile Jüpiter arasında küçük kayalık gök cisimlerinin oluşturduğu kuşağın adı nedir?", c: "Asteroit Kuşağı", yanlislar: ["Oort Bulutu", "Kuiper Kuşağı", "Meteor Yağmuru"] },
    { s: "Plüton hangi kategoride bir gök cismi olarak kabul edilir?", c: "Cüce Gezegen", yanlislar: ["Ana Gezegen", "Uydu", "Kuyruklu Yıldız"] },
    { s: "Mars'ın iki uydusundan biri Phobos'tur, diğerinin adı nedir?", c: "Deimos", yanlislar: ["Titan", "Europa", "Triton"] },
    { s: "Güneş sisteminde halkası olan en büyük dev gezegen hangisidir?", c: "Satürn", yanlislar: ["Jüpiter", "Uranüs", "Neptün"] },
    { s: "Atmosferi olmayan gök cisimlerinde gökyüzü neden her zaman siyah görünür?", c: "Işığı saçacak hava tabakası olmadığı için", yanlislar: ["Güneş ışığı ulaşmadığı için", "Yıldızlar çok uzak olduğu için", "Gök cisimleri karanlık olduğu için"] },
    { s: "Uluslararası Uzay İstasyonu (ISS) dünyamızın etrafında ne yapar?", c: "Yörüngede döner", yanlislar: ["Hareketsiz durur", "Ay'a iniş yapar", "Güneş'e çarpar"] },
    { s: "Yıldızlararası gaz ve toz bulutlarına ne ad verilir?", c: "Nebula (Bulutsu)", yanlislar: ["Pulsar", "Kuasar", "Karadelik"] },
    { s: "Güneş sistemindeki en güçlü manyetik alana sahip gezegen hangisidir?", c: "Jüpiter", yanlislar: ["Dünya", "Satürn", "Neptün"] },
    { s: "Geceleri yönümüzü bulmak için hangi yıldızı takip ederiz?", c: "Kutup Yıldızı", yanlislar: ["Çoban Yıldızı", "Sirius", "Venüs"] },
    { s: "Yıldızların renklerinden hangisi en yüksek yüzey sıcaklığına işaret eder?", c: "Mavi", yanlislar: ["Kırmızı", "Sarı", "Turuncu"] },
    { s: "Uzaya gönderilen ilk yapay uydu olan Sputnik 1 hangi ülke tarafından fırlatılmıştır?", c: "Sovyetler Birliği (SSCB)", yanlislar: ["Amerika", "Çin", "Fransa"] },
    { s: "Ay'a ilk ayak basan insan kimdir?", c: "Neil Armstrong", yanlislar: ["Yuri Gagarin", "Buzz Aldrin", "Elon Musk"] },
    { s: "Uzaya çıkan ilk insan kimdir?", c: "Yuri Gagarin", yanlislar: ["Neil Armstrong", "John Glenn", "Buzz Aldrin"] },
    { s: "Güneş tutulmasında Ay hangi iki gök cismi arasına girer?", c: "Dünya ile Güneş arasına", yanlislar: ["Dünya ile Mars arasına", "Venüs ile Güneş arasına", "Jüpiter ile Dünya arasına"] },
    { s: "Ay tutulmasında hangi gök cismi diğerlerinin ortasında kalır?", c: "Dünya, Güneş ile Ay arasına girer", yanlislar: ["Ay, Güneş'in önüne geçer", "Mars araya girer", "Güneş kaybolur"] },
    { s: "Gökkuşağında kaç tane renk bulunur?", c: "7 renk", yanlislar: ["3 renk", "5 renk", "10 renk"] },
    { s: "Havanın sıcaklığını ölçmek için hangi alet kullanılır?", c: "Termometre", yanlislar: ["Barometre", "Cetvel", "Tartı"] },
    { s: "Atmosfere girip sürtünmeyle yanan göktaşlarına ne denir?", c: "Kayan yıldız (Meteor)", yanlislar: ["Kuyruklu yıldız", "Yapay uydu", "Gezegen"] },
    { s: "Güneş'e en yakın gezegen hangisidir?", c: "Merkür", yanlislar: ["Venüs", "Mars", "Jüpiter"] },
    { s: "Dünya'nın atmosferindeki en bol bulunan gaz hangisidir?", c: "Azot (Nitrojen)", yanlislar: ["Oksijen", "Karbondioksit", "Helyum"] },
    { s: "Dünya'nın haritalarda mavi görünmesinin temel sebebi nedir?", c: "Yüzeyinin sularla kaplı olması", yanlislar: ["Gökyüzünün rengini yansıtması", "Bulutların çok olması", "Dağların mavi olması"] },
    { s: "Güneş sistemindeki en küçük gezegen hangisidir?", c: "Merkür", yanlislar: ["Mars", "Venüs", "Dünya"] },
    { s: "Güneş'in batıdan değil de doğudan doğmasının sebebi nedir?", c: "Dünya'nın batıdan doğuya doğru dönmesi", yanlislar: ["Güneş'in hareket etmesi", "Ay'ın çekim kuvveti", "Yıldızların konumu"] },
    { s: "Hangi gezegenin üzerinde devasa bir 'Büyük Kırmızı Leke' fırtınası vardır?", c: "Jüpiter", yanlislar: ["Satürn", "Mars", "Neptün"] },
    { s: "Halley Kuyruklu Yıldızı dünyamızın yakınından ortalama kaç yılda bir geçer?", c: "75-76 yılda bir", yanlislar: ["10 yılda bir", "100 yılda bir", "1000 yılda bir"] },
    { s: "Uzay boşluğunda ses neden duyulmaz?", c: "Ses dalgalarının yayılacağı hava (ortam) olmadığı için", yanlislar: ["Çok soğuk olduğu için", "Yıldızlar çok uzak olduğu için", "Gezegenler engellediği için"] },
    { s: "Güneş sistemindeki karasal (taşlı) gezegenler hangileridir?", c: "Merkür, Venüs, Dünya, Mars", yanlislar: ["Jüpiter, Satürn, Uranüs, Neptün", "Plüton, Ay, Güneş, Merkür", "Satürn, Mars, Dünya, Venüs"] },
    { s: "Güneş sistemindeki gaz devi gezegenler hangileridir?", c: "Jüpiter, Satürn, Uranüs, Neptün", yanlislar: ["Merkür, Venüs, Dünya, Mars", "Ay, Güneş, Dünya, Satürn", "Mars, Jüpiter, Venüs, Neptün"] },
    { s: "Dünya'nın Güneş etrafındaki yörüngesinin şekli neye benzer?", c: "Elipse (hafif basık daireye)", yanlislar: ["Kareye", "Tam düz bir çizgiye", "Üçgene"] },
    { s: "Yıldızların doğduğu ve gazların sıkıştığı dev bulutlara ne denir?", c: "Nebula", yanlislar: ["Asteroit", "Meteor", "Galaksi"] },
    { s: "Güneş sistemindeki en soğuk gezegen hangisidir?", c: "Uranüs", yanlislar: ["Merkür", "Mars", "Satürn"] },
    { s: "Uzay araçlarının Dünya'nın çekim kuvvetinden kurtulup uzaya çıkabilmesi için ne gerekir?", c: "Çok yüksek hız ve güçlü roketler", yanlislar: ["Kürek çekmek", "Rüzgar arkasına almak", "Güneş'e yaklaşmak"] },
    { s: "Güneş lekesi nedir?", c: "Güneş'in diğer bölgelerine göre daha soğuk ve karanlık alanları", yanlislar: ["Güneş'in üzerindeki taşlar", "Güneş'in gölgesi", "Güneş'in delikleri"] },
    { s: "Ay'ın Dünya'ya bakan yüzü ile arka yüzü hakkında ne söylenebilir?", c: "Hep aynı yüzü dünyaya bakar", yanlislar: ["Sürekli döner ve her yerini görürüz", "Sadece geceleri görünür", "Gündüzleri kaybolur"] },
    { s: "Yıldız kayması denilen olay aslında gercekte nedir?", c: "Atmosfere giren küçük bir gök taşının yanması", yanlislar: ["Gerçek bir yıldızın yer değiştirmesi", "Ay'ın parlaması", "Uçak ışığı"] },
    { s: "Güneş tutulması hangi evrede gerçekleşir?", c: "Yeni Ay evresinde", yanlislar: ["Dolunay evresinde", "İlk dördünde", "Son dördünde"] },
    { s: "Ay tutulması hangi evrede gerçekleşir?", c: "Dolunay evresinde", yanlislar: ["Yeni Ay evresinde", "Hilal evresinde", "İlk dördünde"] },
    { s: "Uzayda astronotların su içerken veya yerken yaşadığı en büyük zorluk nedir?", c: "Yerçekimsizlikten ötürü yiyeceklerin ve suyun havada uçuşması", yanlislar: ["Çok sıcak olması", "Yiyecek bulamamaları", "Ses duyamamaları"] },
    { s: "Güneş'in rengi uzaydan bakıldığında asıl olarak ne renktir?", c: "Beyaz", yanlislar: ["Sarı", "Kırmızı", "Mavi"] },
    { s: "Hangi gezegenin halkaları teleskop olmadan bile küçük bir gözlemle fark edilebilir?", c: "Satürn'ün", yanlislar: ["Jüpiter'in", "Neptün'ün", "Mars'ın"] },
    { s: "Dünya'nın kendi ekseni etrafındaki dönüş yönü hangisidir?", c: "Batıdan doğuya doğru", yanlislar: ["Doğudan batıya doğru", "Kuzeyden güneye doğru", "Sabit durur"] },
    { s: "Güneş sistemindeki en büyük volkanik dağ olan Olympus Mons kaç kilometre yüksekliktedir?", c: "Yaklaşık 22 kilometre", yanlislar: ["5 kilometre", "8 kilometre", "50 kilometre"] },
    { s: "Uzak galaksileri incelemek için kullanılan en ünlü uzay teleskobunun adı nedir?", c: "Hubble Uzay Teleskobu", yanlislar: ["Newton Teleskobu", "Galileo Dürbünü", "Einstein Cihazı"] },
    { s: "Mars gezegeninin toprak yapısında neden bolca demir oksit (pas) bulunur?", c: "Yüzeyinin pas renginde toz ve taşlarla kaplı olmasından", yanlislar: ["Çok fazla su olduğu için", "Fabrikalar kurulduğu için", "Bitki örtüsü nedeniyle"] },
    { s: "Güneş sistemindeki en büyük uydunun adı nedir?", c: "Ganymede (Jüpiter'in uydusu)", yanlislar: ["Titan", "Ay", "Europa"] },
    { s: "Satürn'ün en büyük uydusunun adı nedir?", c: "Titan", yanlislar: ["Ganymede", "Phobos", "Io"] },
    { s: "Güneş sisteminde uydusu olmayan gezegenler hangileridir?", c: "Merkür ve Venüs", yanlislar: ["Dünya ve Mars", "Uranüs ve Neptün", "Jüpiter ve Satürn"] },
    { s: "Bir ışık yılı neyi ölçmek için kullanılan birimdir?", c: "Uzaklık (mesafe)", yanlislar: ["Zaman", "Hız", "Sıcaklık"] },
    { s: "Dünya'mızın şekli tam olarak nasıl tanımlanır?", c: "Kutuplardan basık, ekvatordan şişkin küre (Geoid)", yanlislar: ["Tam kusursuz bir top", "Kare prizma", "Düz tepsi"] },
    { s: "Gök cisimlerinin birbirine uyguladığı çekim kuvvetine ne denir?", c: "Kütleçekim (Yerçekimi)", yanlislar: ["Manyetik kuvvet", "Elektrik akımı", "Rüzgar gücü"] },
    { s: "Yıldızların ömrünün sonuna gelip devasa bir patlama yapmasına ne denir?", c: "Süpernova", yanlislar: ["Meteor yağmuru", "Güneş fırtınası", "Deprem"] },
    { s: "Işık hızı saniyede yaklaşık kaç kilometredir?", c: "300.000 kilometre", yanlislar: ["3.000 kilometre", "30 kilometre", "3 milyon kilometre"] },
    { s: "Güneş'in yüzey sıcaklığı yaklaşık kaç derecedir?", c: "5.500 derece", yanlislar: ["100 derece", "1 milyon derece", "50 derece"] },
    { s: "Güneş'in çekirdek sıcaklığı yüzeyine göre nasıldır?", c: "Çok daha sıcaktır (milyonlarca derece)", yanlislar: ["Daha soğuktur", "Aynıdır", "Değişmez"] },
    { s: "Atmosferimiz bizi Güneş'in hangi zararlı ışınlarından korur?", c: "Ultraviyole (morötesi) ışınlar", yanlislar: ["Görünür ışık", "Radyo dalgaları", "Ses dalgaları"] },
    { s: "Kutup bölgelerinde gökyüzünde görülen renkli ışık gösterilerine ne ad verilir?", c: "Aurora (Kutup Işıkları)", yanlislar: ["Şimşek", "Gökkuşağı", "Yıldız kayması"] },
    { s: "Uzaya fırlatılan roketlerin ilk aşamada yenmesi gereken en büyük güç nedir?", c: "Dünya'nın yerçekimi", yanlislar: ["Ay'ın rüzgarı", "Bulutların direnci", "Güneş'in ısısı"] },
    { s: "Venüs gezegenine halk arasında ne ad verilir?", c: "Çoban Yıldızı (Saba Yıldızı)", yanlislar: ["Kızıl Yıldız", "Demir Yıldız", "Mavi Küre"] },
    { s: "Güneş sistemindeki en hızlı dönen gezegen hangisidir?", c: "Jüpiter", yanlislar: ["Merkür", "Dünya", "Neptün"] },
    { s: "Güneş sisteminde Güneş'e en uzak olan gezegen hangisidir?", c: "Neptün", yanlislar: ["Uranüs", "Satürn", "Plüton"] },
    { s: "Ay'ın Dünya etrafındaki bir tam tur dönüşü ne kadar sürer?", c: "Yaklaşık 27.3 gün", yanlislar: ["24 saat", "365 gün", "7 gün"] },
    { s: "Güneş sistemindeki asteroit kuşağı hangi gezegenler arasındadır?", c: "Mars ile Jüpiter", yanlislar: ["Dünya ile Mars", "Jüpiter ile Satürn", "Venüs ile Dünya"] },
    { s: "Gökbilimciler uzaktaki cisimlerin uzaklığını hesaplarken neyi baz alırlar?", c: "Işığın yayılma ve renk kayması süresini", yanlislar: ["Uçağın hızını", "Ses dalgalarını", "Rüzgarın yönünü"] },
    { s: "Aşağıdakilerden hangisi bir takımyıldız adıdır?", c: "Büyük Ayı", yanlislar: ["Samanyolu", "Andromeda", "Güneş"] },
    { s: "Uzay istasyonlarında suyun geri dönüştürülmesi neden hayati önem taşır?", c: "Dünya'dan sürekli su taşımak çok maliyetli olduğu için", yanlislar: ["Uzayda su yasak olduğu için", "Su hemen buharlaştığı için", "Astronotlar su içmediği için"] },
    { s: "Güneş sistemindeki en büyük cüce gezegen hangisidir?", c: "Plüton", yanlislar: ["Ceres", "Eris", "Haumea"] },
    { s: "Dünya'nın katmanlarından hangisi üzerinde yaşadığımız en dış kısımdır?", c: "Yer kabuğu (Litosfer)", yanlislar: ["Çekirdek", "Manto", "Magma tabakası"] },
    { s: "Güneş'e en uzak olan buz devi gezegen hangisidir?", c: "Neptün", yanlislar: ["Uranüs", "Satürn", "Jüpiter"] },
    { s: "Ay'ın Dünya'ya en yakın olduğu konuma ne ad verilir?", c: "Yerberi (Perigee)", yanlislar: ["Yeröte", "Tutulma", "Dönence"] },
    { s: "Gökyüzünde kayan yıldız olarak gördüğümüz taş parçaları aslında nereye düşer?", c: "Atmosfere girip yanarlar", yanlislar: ["Direkt denize düşerler", "Ay'a çarparlar", "Güneş'e giderler"] },
    { s: "Güneş sisteminde yaşam barındırdığı bilinen tek gök cismi hangisidir?", c: "Dünya", yanlislar: ["Mars", "Venüs", "Ay"] },
    { s: "Uzay elbiseleri astronotları öncelikli olarak hangi tehlikeden korur?", c: "Havasızlık, aşırı sıcaklık ve zararlı radyasyondan", yanlislar: ["Sadece yağmurdan", "Uçak çarpmasından", "Karanlıktan"] },
    { s: "Ay'ın etrafımızda dönerken aldığı şekillere ne denir?", c: "Ay'ın evreleri", yanlislar: ["Gezegen halleri", "Yıldız formları", "Işık oyunları"] },
    { s: "Güneş enerjisi temel olarak hangi nükleer olayla üretilir?", c: "Füzyon (birleşme)", yanlislar: ["Fisyon (bölünme)", "Yanma", "Paslanma"] },
    { s: "Güneş sistemindeki kayalık gezegenlerin ortak özelliği nedir?", c: "Sert bir yüzeye sahip olmaları", yanlislar: ["Halkalarının olması", "Çok büyük olmaları", "Gazdan oluşmaları"] },
    { s: "Güneş sistemindeki en büyük gaz devi hangisidir?", c: "Jüpiter", yanlislar: ["Dünya", "Mars", "Venüs"] },
    { s: "Ay'ın yüzeyinde yürüyen ilk uzay aracı insanlı mıdır?", c: "Evet (Apollo 11 ile)", yanlislar: ["Hayır, tamamen robottu", "Hiçbir zaman gidilmedi", "Sadece uydu gönderildi"] },
    { s: "Dünya'nın uydusu olan Ay, gece neden parlar?", c: "Güneş'ten aldığı ışığı yansıttığı için", yanlislar: ["Kendi ışığı olduğu için", "Yıldız gibi yandığı için", "Bulutlar parlattığı için"] },
    { s: "Hangi gezegen kırmızı görünümüyle bilinir?", c: "Mars", yanlislar: ["Satürn", "Neptün", "Merkür"] },
    { s: "Güneş sistemindeki en sıcak gezegen hangisidir?", c: "Venüs", yanlislar: ["Merkür", "Mars", "Jüpiter"] },
    { s: "Uranüs ve Neptün hangi renkleriyle bilinirler?", c: "Mavi-yeşil (buz devi tonları)", yanlislar: ["Kırmızı ve sarı", "Kömür karası", "Parlak altın sarısı"] },
    { s: "Güneş sisteminde yaşamın olabileceği düşünülen sıvı sular barındıran Jüpiter uydusu hangisidir?", c: "Europa", yanlislar: ["Titan", "Phobos", "Deimos"] },
    { s: "Astronotların uzayda giydiği özel kıyafete ne ad verilir?", c: "Uzay giysisi (Kondisyon tulumu)", yanlislar: ["Dalgıç kıyafeti", "İtfaiyeci elbisesi", "Pilot ceketi"] },
    { s: "Güneş'in etrafında dönen gök cisimlerinin izlediği yola ne denir?", c: "Yörünge", yanlislar: ["Otoban", "Hattı", "Rota çizgisi"] },
    { s: "Yıldızların gökyüzünde belirli şekiller oluşturduğu hayali gruplara ne denir?", c: "Takımyıldız (Konstelasyon)", yanlislar: ["Bulutsu kümesi", "Galaksi kolu", "Asteroit ağı"] },
    { s: "Dünya'nın kendi ekseni etrafında dönmesi sonucunda ne gerçekleşir?", c: "Gece ve gündüz", yanlislar: ["Mevsimler", "Yıllar", "Ay tutulması"] },
    { s: "Dünya'nın Güneş etrafında dönmesi sonucunda ne oluşur?", c: "Mevsimler ve 1 yıl", yanlislar: ["Gece ve gündüz", "Rüzgar", "Med-cezir"] },
    { s: "Güneş sistemindeki en büyük dağ olan Olympus Mons nerededir?", c: "Mars", yanlislar: ["Dünya", "Venüs", "Satürn"] },
    { s: "Hangi gezegenin halkaları en belirgin ve büyüktür?", c: "Satürn", yanlislar: ["Jüpiter", "Uranüs", "Merkür"] },
    { s: "Güneş'ten sonra dünyaya en yakın yıldızın adı nedir?", c: "Proxima Centauri (Alpha Centauri sistemi)", yanlislar: ["Sirius", "Polaris", "Betelgeuse"] },
    { s: "Atmosferi olmayan ve göktaşlarının sürekli çarptığı kraterli gök cismi hangisidir?", c: "Ay", yanlislar: ["Dünya", "Jüpiter", "Güneş"] },
    { s: "Güneş sisteminde kaç tane gaz devi gezegen vardır?", c: "2 (Jüpiter ve Satürn)", yanlislar: ["4", "1", "8"] },
    { s: "Güneş sisteminde kaç tane buz devi gezegen vardır?", c: "2 (Uranüs ve Neptün)", yanlislar: ["3", "5", "Hiç yoktur"] },
    { s: "Güneş doğudan doğduğunda hangi yönden batar?", c: "Batıdan", yanlislar: ["Kuzeyden", "Güneyden", "Yukarından"] },
    { s: "Uluslararası Uzay İstasyonu (ISS) dünyadan bakıldığında ne olarak görünür?", c: "Hızlıca geçen parlak bir ışık noktası", yanlislar: ["Büyük bir uçak", "Kuyruklu yıldız", "Sabit duran bir yıldız"] },
    { s: "Dünya'nın en büyük okyanusu hangisidir?", c: "Pasifik (Büyük Okyanus)", yanlislar: ["Atlas Okyanusu", "Hint Okyanusu", "Arktik"] },
    { s: "Hangi gök cismi kendi ışığını üretir?", c: "Yıldızlar", yanlislar: ["Gezegenler", "Uydular", "Asteroitler"] },
    { s: "Hangi gök cismi kendi ışığını üretemez, sadece yansıtır?", c: "Gezegenler", yanlislar: ["Yıldızlar", "Güneş", "Pulsarlar"] },
    { s: "Uzay araştırmalarında roketlerin fırlatıldığı tesislere ne denir?", c: "Uzay üssü (Fırlatma merkezi)", yanlislar: ["Havaalanı", "Garaj", "Gözlemevi"] },
    { s: "Ay'ın Dünya etrafındaki bir tam tur hareketi yaklaşık ne kadar sürer?", c: "1 ay (29.5 gün)", yanlislar: ["24 saat", "1 yıl", "1 hafta"] },
    { s: "Güneş ışığı dünyaya kaç saniyede veya dakikada gelir?", c: "Yaklaşık 8 dakikada", yanlislar: ["1 saniyede", "2 saatte", "1 günde"] },
    { s: "Mars'ın yüzeyindeki toprak rengi neye benzetilir?", c: "Kiremit veya pas rengine", yanlislar: ["Bembeyaz kara", "Masmavi suya", "Yeşil çimene"] },
    { s: "Jüpiter'in en büyük uydusunun adı nedir?", c: "Ganymede", yanlislar: ["Titan", "Io", "Europa"] },
    { s: "Satürn'ün en ünlü büyük uydusu hangisidir?", c: "Titan", yanlislar: ["Ganymede", "Callisto", "Phobos"] },
    { s: "Hangi gezegen saat yönünün tersine dönmesiyle ve sıcağıyla bilinir?", c: "Venüs", yanlislar: ["Mars", "Dünya", "Neptün"] },
    { s: "Güneş sistemindeki en hızlı gezegen hangisidir?", c: "Merkür", yanlislar: ["Neptün", "Dünya", "Satürn"] },
    { s: "Dünya'nın katmanları arasında en sıcak yer neresidir?", c: "Merkez (İekirdek)", yanlislar: ["Yer kabuğu", "Atmosfer", "Okyanus tabanı"] },
    { s: "Geceleri yön bulmak için kullanılan Kutup Yıldızı hangi takımyıldızındadır?", c: "Küçük Ayı", yanlislar: ["Büyük Ayı", "Orion", "Ejderha"] },
    { s: "Gökyüzünde avcı olarak bilinen ünlü takımyıldız hangisidir?", c: "Orion (Avcı)", yanlislar: ["Kutup", "Yılan", "Kuğu"] },
    { s: "Yıldızların doğduğu gaz ve toz bulutlarına ne denir?", c: "Nebula", yanlislar: ["Galaksi", "Kuyruklu yıldız", "Kara delik"] },
    { s: "Samanyolu galaksisi dışındaki en yakın büyük spiral galaksi hangisidir?", c: "Andromeda", yanlislar: ["Sombrero", "Üçgen", "Magellan"] },
    { s: "Evrendeki tüm madde, enerji, uzay ve zamanın tamamına ne denir?", c: "Evren (Kainat)", yanlislar: ["Güneş sistemi", "Samanyolu", "Boşluk"] },
    { s: "Güneş sisteminde güneşe en yakın 3. gezegen hangisidir?", c: "Dünya", yanlislar: ["Merkür", "Venüs", "Mars"] },
    { s: "Güneş sisteminde güneşe en uzak ana gezegen hangisidir?", c: "Neptün", yanlislar: ["Uranüs", "Satürn", "Jüpiter"] },
    { s: "Hangi gezegenin eksen eğikliği neredeyse 90 derece yan yatmıştır?", c: "Uranüs", yanlislar: ["Satürn", "Neptün", "Dünya"] },
    { s: "Dünya'nın şekli neye benzetilir?", c: "Kutuplardan basık küreye (Geoid)", yanlislar: ["Kutu", "Mükemmel daire", "Silindire"] },
    { s: "Güneş'in yüzeyindeki lekeler neden karanlık görünür?", c: "Diğer yerlere göre daha soğuk olduğu için", yanlislar: ["Üzerinde bulut olduğu için", "Delik olduğu için", "Gölge düştüğü için"] },
    { s: "Ay'ın Dünya'dan görünmeyen yüzüne ne ad verilir?", c: "Ay'ın karanlık yüzü", yanlislar: ["Arka sokak", "Görünmez duvar", "Uzak nokta"] },
    { s: "Roketlerin uzaya çıkarken kullandığı yakıtlar nasıldır?", c: "Çok güçlü sıvı ve katı roket yakıtları", yanlislar: ["Normal benzin", "Mazot", "Elektrik bataryası"] },
    { s: "Astronotlar uzayda yerçekimi olmadığı için nasıl hareket ederler?", c: "Süzülerek ve zıplayarak", yanlislar: ["Koşarak", "Sürünerek", "Yüzerek"] },
    { s: "Güneş sistemindeki en küçük uydu hangisidir?", c: "Deimos (Mars'ın uydusu)", yanlislar: ["Ay", "Titan", "Ganymede"] },
    { s: "Gökyüzünde 7 yıldızdan oluşan ve tencereye benzetilen şeklin adı nedir?", c: "Büyük Kepçe (Büyük Ayı'nın parçası)", yanlislar: ["Küçük Kepçe", "Çoban", "Kartal"] },
    { s: "Güneş tutulması sırasında güneşe doğrudan çıplak gözle bakmak neden zararlıdır?", c: "Göz retinasını yakıp körlüğe sebep olabileceği için", yanlislar: ["Hiçbir zararı yoktur", "Sadece gözü yorar", "Baş ağrısı yapar"] },
    { s: "Ay'ın ana evreleri kaç tanedir?", c: "4 temel evre (Yeni ay, İlk dördün, Dolunay, Son dördün)", yanlislar: ["2", "10", "1"] },
    { s: "Güneş'in dünyaya olan mesafesi yaklaşık kaç kilometredir?", c: "150 milyon kilometre", yanlislar: ["15 bin kilometre", "10 milyon kilometre", "1 milyar kilometre"] },
    { s: "Dünya'nın etrafını saran gaz tabakasına ne ad verilir?", c: "Atmosfer", yanlislar: ["Ozon deligi", "Kabuk", "Stratosfer tabanı"] },
    { s: "Atmosferin en alt katmanında hangi olaylar gerçekleşir?", c: "Hava olayları (Yağmur, rüzgar vb.)", yanlislar: ["Yıldız kayması", "Güneş patlaması", "Kuyruklu yıldız geçişi"] },
    { s: "Güneş sistemindeki gezegenlerin yörüngeleri ne şeklindedir?", c: "Elips", yanlislar: ["Kare", "Üçgen", "Düz çizgi"] },
    { s: "Bir göktaşının atmosferi geçip yeryüzüne düşen parçasına ne denir?", c: "Meteorit (Göktaşı)", yanlislar: ["Kuyruklu yıldız", "Nebula", "Yapay uydu"] },
    { s: "Ay'a ilk insan hangi uzay aracıyla gitmiştir?", c: "Apollo 11", yanlislar: ["Sputnik 1", "Voyager", "Discovery"] },
    { s: "Uzaydaki kara delikler maddeleri neden içine çeker?", c: "Çok güçlü kütleçekim kuvveti olduğu için", yanlislar: ["Mıknatıs gibi oldukları için", "Çok rüzgar estirdikleri için", "Sıcak oldukları için"] },
    { s: "Güneş rüzgarları dünyaya ulaştığında kutuplarda ne yaratır?", c: "Kutup ışıkları (Aurora)", yanlislar: ["Deprem", "Tsunami", "Yanardağ patlaması"] },
    { s: "Güneş sistemimiz hangi galaksi kümesinde yer alır?", c: "Yerel Galaksi Grubu", yanlislar: ["Başak Kümesi", "Andromeda Kümesi", "Samanyolu Ailesi"] },
    { s: "Yıldızların ömrü bittiğinde patlaması sonucu oluşan çok yoğun küreye ne denir?", c: "Nötron yıldızı", yanlislar: ["Gaz bulutu", "Sarı cüce", "Kuyruklu yıldız"] },
    { s: "Dünya kendi etrafındaki bir turunu hangi yönde tamamlar?", c: "Batıdan doğuya", yanlislar: ["Doğudan batıya", "Kuzeyden güneye", "Güneyden kuzeye"] },
    { s: "Hangi gezegenin ringleri (halkaları) ilk kez Galileo tarafından gözlemlenmiştir?", c: "Satürn", yanlislar: ["Jüpiter", "Neptün", "Uranüs"] },
    { s: "Güneş sistemindeki en büyük volkanik dağ olan Olympus Mons kaç metredir?", c: "Yaklaşık 22.000 metre (22 km)", yanlislar: ["500 metre", "8.848 metre", "50.000 metre"] },
    { s: "Güneş'in dünyaya en yakın olduğu döneme ne ad verilir?", c: "Günberi (Perihel)", yanlislar: ["Günöte", "Tutulma", "Denge"] },
    { s: "Güneş'in dünyaya en uzak olduğu döneme ne ad verilir?", c: "Günöte (Aphel)", yanlislar: ["Günberi", "Ekinoks", "Solstice"] },
    { s: "Yılın en uzun gecesinin yaşandığı güne ne denir?", c: "Kış gündönümü (21 Aralık)", yanlislar: ["Yaz gündönümü", "Ekinoks", "Bahar başlangıcı"] },
    { s: "Gece ve gündüzün eşit olduğu tarihlere ne denir?", c: "Ekinoks (21 Mart / 23 Eylül)", yanlislar: ["Gündönümü", "Tutulma", "Zirve"] },
    { s: "Uzay çalışmalarında kullanılan Hubble'dan sonraki en büyük uzay teleskobu hangisidir?", c: "James Webb Uzay Teleskobu", yanlislar: ["Kepler", "Spitzer", "Chandra"] },
    { s: "Güneş sistemindeki en büyük kraterlerden biri hangi gezegendedir?", c: "Merkür (Caloris Havzası)", yanlislar: ["Dünya", "Satürn", "Venüs"] },
    { s: "Gökbilimde mesafeleri ölçmek için kullanılan ışık yılı neyin birimidir?", c: "Uzaklık (Mesafe)", yanlislar: ["Zaman", "Hız", "Ağırlık"] },
    { s: "Dünya'nın manyetik alanı bizi neyden korur?", c: "Güneş'ten gelen zararlı yüklü parçacıklardan (rüzgarlardan)", yanlislar: ["Göktaşlarından", "Ufolardan", "Ay'ın çekiminden"] },
    { s: "Uydumuz Ay, dünyadan her yıl yavaşça uzaklaşmakta mıdır?", c: "Evet, yılda birkaç santimetre uzaklaşır", yanlislar: ["Hayır, her yıl yaklaşır", "Sabit durur", "Hızla uzaklaşıp kaybolacaktır"] },
    { s: "Güneş sistemindeki uydular arasında kalın bir atmosferi olan tek uydu hangisidir?", c: "Titan", yanlislar: ["Europa", "Ganymede", "Phobos"] },
    { s: "Yıldızlararası maddelerin ve gazların oluşturduğu bulutlara genel olarak ne denir?", c: "Bulutsu (Nebula)", yanlislar: ["Galaksi", "Kuyruklu yıldız", "Asteroit"] },
    { s: "Dünya dışı yaşamı ve akıllı medeniyetleri inceleyen bilim dalı hangisidir?", c: "Astrorobiyoloji / SETI", yanlislar: ["Meteoroloji", "Jeoloji", "Paleontoloji"] },
    { s: "Güneş sisteminde halkası olan gezegenler gaz ve buz devleridir; bunlardan halkası olmayan var mıdır?", c: "Yoktur, dördünün de halkası vardır", yanlislar: ["Jüpiter'in yoktur", "Neptün'ün yoktur", "Uranüs'ün yoktur"] },
    { s: "Mars'ın iki uydusunun adları nelerdir?", c: "Phobos ve Deimos", yanlislar: ["Titan ve Europa", "Io ve Ganymede", "Atlas ve Prometheus"] },
    { s: "Güneş ışınlarının dünyaya dik geldiği çizgiye ne ad verilir?", c: "Ekvator", yanlislar: ["Meridyen", "Kutup çizgisi", "Yengeç dönencesi"] },
    { s: "Güneş'in etrafında dönen ve buz ile kayadan oluşan, kuyruğu olan cisimlere ne denir?", c: "Kuyruklu yıldız", yanlislar: ["Meteor", "Asteroit", "Yapay uydu"] },
    { s: "Uzay mekiği nedir?", c: "Dünya ile uzay istasyonu arasında tekrar kullanılabilen taşıt", yanlislar: ["Tek kullanımlık roket", "Uzay çöpü", "Ay aracı"] },
    { s: "Güneş'in ömrünün sonunda dönüşeceği yıldız türü nedir?", c: "Beyaz cüce", yanlislar: ["Karadelik", "Nötron yıldızı", "Süpernova"] },
    { s: "Güneş sistemindeki en büyük volkanik dağ olan Olympus Mons kaç yanardağın birleşimi gibidir?", c: "Devasa tek bir kalkan volkandır", yanlislar: ["İki dağın", "Yüzlerce küçük volkanın", "Sönmüş sıradağların"] },
    { s: "Dünya'nın güneşe en yakın olduğu ay hangisidir?", c: "Ocak", yanlislar: ["Temmuz", "Mart", "Eylül"] },
    { s: "Dünya'nın güneşe en uzak olduğu ay hangisidir?", c: "Temmuz", yanlislar: ["Ocak", "Aralık", "Şubat"] },
    { s: "Güneş sistemindeki en büyük manyetik alana sahip gezegenin uydusu olan Ganymede hangi gezegene aittir?", c: "Jüpiter", yanlislar: ["Satürn", "Uranüs", "Neptün"] },
    { s: "Ay'ın yerçekimi kuvveti Dünya'nın yerçekiminin yaklaşık kaçta kaçıdır?", c: "Altıda biri (1/6)", yanlislar: ["Yarısı (1/2)", "Onda biri (1/10)", "Aynıdır"] },
    { s: "Güneş tutulması sırasında ayın gölgesi dünya üzerinde ne oluşturur?", c: "Karanlık bir bölge (Tam gölge kuşağı)", yanlislar: ["Işık seli", "Deprem dalgası", "Renkli bulut"] },
    { s: "Gökbilimciler gök cisimlerinin parlaklığını ölçmek için hangi ölçeği kullanır?", c: "Kadir (Magnitude) ölçeği", yanlislar: ["Kilogram", "Desibel", "Celsius"] },
    { s: "Samanyolu galaksisinin merkezinde ne olduğu düşünülmektedir?", c: "Dev bir süper kütleli karadelik", yanlislar: ["Dev bir güneş", "Kocaman bir elmas", "Boşluk"] },
    { s: "Güneş enerjisi dünyaya hangi yolla ulaşır?", c: "Işıma (Radyasyon) yoluyla", yanlislar: ["İletim yoluyla", "Taşıma yoluyla", "Rüzgarla"] },
    { s: "Astronotlar uzay istasyonunda kas erimesini önlemek için ne yaparlar?", c: "Her gün spor ve egzersiz yaparlar", yanlislar: ["Süt içerler", "Güneşlenirler", "Hareketsiz yatarlar"] },
    { s: "Güneş sistemindeki gezegenler güneşe olan mesafelerine göre nasıl sıralanır?", c: "Merkür, Venüs, Dünya, Mars, Jüpiter, Satürn, Uranüs, Neptün", yanlislar: ["Dünya, Mars, Jüpiter...", "Satürn, Jüpiter, Mars...", "Neptün, Uranüs..."] },
    { s: "Hangi gezegenin atmosferi ağırlıklı olarak karbondioksitten oluşur ve sera etkisiyle çok sıcaktır?", c: "Venüs", yanlislar: ["Mars", "Dünya", "Merkür"] },
    { s: "Mars gezegeninde suyun varlığı geçmişte hangi formda aranmaktadır?", c: "Sıvı nehir ve göl yatakları kalıntılarında", yanlislar: ["Buzul dağlarında", "Bulutlarda", "Yağmur ormanlarında"] },
    { s: "Güneş bir galaksinin merkezinde midir, yoksa kenarında mı?", c: "Kenara yakın bir kolunda", yanlislar: ["Tam merkezindedir", "Galaksinin dışındadır", "Hiçbir galakside değildir"] },
    { s: "Dünya'nın eksen eğikliği olmasaydı ne olurdu?", c: "Mevsimler oluşmazdı", yanlislar: ["Gece ve gündüz olmazdı", "Yerçekimi kalkardı", "Yıl 100 gün olurdu"] },
    { s: "Güneş sistemindeki en büyük kanyon olan Valles Marineris kaç kilometre uzunluğundadır?", c: "Binlerce kilometre (4000 km)", yanlislar: ["10 kilometre", "50 kilometre", "100 kilometre"] },
    { s: "Uzay boşluğunda yön bulmak için ne kullanılır?", c: "Yıldız haritaları ve takımyıldızlar", yanlislar: ["Pusula", "GPS cihazı", "Harita"] },
    { s: "Ay'ın yüzeyinde insan ayak izleri neden milyonlarca yıl kalabilir?", c: "Rüzgar ve hava akımı olmadığı için silinmez", yanlislar: ["Çok sert taş olduğu için", "Üzerine beton döküldüğü için", "Ay hiç dönmediği için"] },
    { s: "Güneş'in yaşı yaklaşık olarak kaç yıldır?", c: "4.6 milyar yıl", yanlislar: ["5 bin yıl", "10 milyon yıl", "100 milyar yıl"] },
    { s: "Dünya'nın etrafını saran hava katmanına ne denir?", c: "Atmosfer", yanlislar: ["Okyanus", "Kabuk", "Taş tabakası"] },
    { s: "Güneş sistemindeki en büyük ikinci gezegen hangisidir?", c: "Satürn", yanlislar: ["Uranüs", "Neptün", "Dünya"] },
    { s: "Güneş sisteminde Güneş'e en yakın olan buz devi gezegen hangisidir?", c: "Uranüs", yanlislar: ["Neptün", "Satürn", "Jüpiter"] },
    { s: "Geceleri gökyüzünde gördüğümüz Ay hangi aşamada tamamen parlak bir daire gibi görünür?", c: "Dolunay", yanlislar: ["Yeni Ay", "Hilal", "Son dördün"] },
    { s: "Güneş tutulması sırasında Ay nereye geçer?", c: "Dünya ile Güneş arasına", yanlislar: ["Dünya'nın arkasına", "Mars'ın yanına", "Uzayın dışına"] },
    { s: "Gökbilimciler gökyüzünü incelemek için öncelikle ne kullanırlar?", c: "Teleskop", yanlislar: ["Mikroskop", "Büyüteç", "Dürbün"] },
    { s: "Güneş sistemindeki en yüksek dağ olan Olympus Mons hangi gezegendedir?", c: "Mars", yanlislar: ["Venüs", "Dünya", "Merkür"] },
    { s: "Aşağıdakilerden hangisi bir kuyruklu yıldız adıdır?", c: "Halley", yanlislar: ["Sputnik", "Apollo", "Hubble"] },
    { s: "Yıldızların ömrünün sonunda patlamasına ne denir?", c: "Süpernova", yanlislar: ["Meteor yağmuru", "Güneş rüzgarı", "Deprem"] },
    { s: "Uzay istasyonlarında yerçekimi olmamasının sebebi nedir?", c: "Sürekli serbest düşme yörüngesinde olmaları", yanlislar: ["Havanın olmaması", "Güneş'in itmesi", "Dünya'dan çok uzak olmaları"] },
    { s: "Güneş'in yüzeyinde oluşan daha karanlık ve soğuk bölgelere ne ad verilir?", c: "Güneş lekesi", yanlislar: ["Güneş çukuru", "Krater", "Bulut"] },
    { s: "Yıldızlararası boşlukta en çok bulunan element hangisidir?", c: "Hidrojen", yanlislar: ["Oksijen", "Demir", "Karbondioksit"] },
    { s: "Dünya'nın Güneş etrafındaki dönüşü neyi oluşturur?", c: "Yılları ve mevsimleri", yanlislar: ["Geceyi ve gündüzü", "Rüzgarları", "Gel-giti"] },
    { s: "Dünya'nın kendi ekseni etrafındaki dönüşü neyi oluşturur?", c: "Gece ve gündüzü", yanlislar: ["Mevsimleri", "Yılları", "Ay'ın evrelerini"] },
    { s: "Güneş sistemindeki en büyük uydunun adı nedir?", c: "Ganymede", yanlislar: ["Titan", "Europa", "Ay"] },
    { s: "Satürn'ün en büyük uydusunun adı nedir?", c: "Titan", yanlislar: ["Phobos", "Deimos", "Io"] },
    { s: "Mars gezegeninin iki uydusundan biri Phobos'tur, diğeri hangisidir?", c: "Deimos", yanlislar: ["Titan", "Europa", "Callisto"] },
    { s: "Güneş sisteminde uydusu olmayan gezegenler hangileridir?", c: "Merkür ve Venüs", yanlislar: ["Dünya ve Mars", "Uranüs ve Neptün", "Jüpiter ve Satürn"] },
    { s: "Uranüs gezegeni sistemde nasıl döner?", c: "Yan yatmış bir varil gibi", yanlislar: ["Çok hızlı bir şekilde dikine", "Ters yönde dümdüz", "Hareketsiz durarak"] },
    { s: "Venüs gezegeninin en büyük özelliği nedir?", c: "Güneş sisteminin en sıcak gezegeni olması", yanlislar: ["En büyük gezegen olması", "Halkalarının olması", "Uydusunun olmaması"] },
    { s: "Merkür gezegeninin yüzeyi neye benzer?", c: "Ay'ın yüzeyindeki kraterli yapıya", yanlislar: ["Dünya'nın okyanuslarına", "Jüpiter'in bulutlarına", "Buz tabakasına"] },
    { s: "Güneş sistemindeki en şiddetli rüzgarlar hangi gezegende eser?", c: "Neptün", yanlislar: ["Merkür", "Mars", "Venüs"] },
    { s: "Güneş'e en uzak olan ana gezegen hangisidir?", c: "Neptün", yanlislar: ["Uranüs", "Satürn", "Plüton"] },
    { s: "Güneş sisteminde halkası olan en büyük gezegen hangisidir?", c: "Satürn", yanlislar: ["Jüpiter", "Neptün", "Uranüs"] },
    { s: "Yıldızların renkleri bize ne hakkında bilgi verir?", c: "Sıcaklıkları hakkında", yanlislar: ["Uzaklıkları hakkında", "Büyüklükleri hakkında", "Ağırlıkları hakkında"] },
    { s: "En sıcak yıldızlar hangi renk görünürler?", c: "Mavi", yanlislar: ["Kırmızı", "Sarı", "Turuncu"] },
    { s: "En soğuk yıldızlar hangi renk görünürler?", c: "Kırmızı", yanlislar: ["Mavi", "Beyaz", "Yeşil"] },
    { s: "Güneş bir yıldız olarak hangi renk görünür?", c: "Sarı (Uzaydan beyaz)", yanlislar: ["Kırmızı", "Mavi", "Mor"] },
    { s: "Dünya'mızın şekli tam olarak nedir?", c: "Basık küre (Geoid)", yanlislar: ["Düz bir tepsi", "Tam daire", "Küp"] },
    { s: "Gök cisimleri arasındaki mesafeyi ölçmek için kullanılan birim nedir?", c: "Işık yılı", yanlislar: ["Kilometre saati", "Metre", "Mil"] },
    { s: "Işık boşlukta bir saniyede yaklaşık kaç kilometre yol alır?", c: "300.000 kilometre", yanlislar: ["3.000 kilometre", "30 kilometre", "3 milyon kilometre"] },
    { s: "Güneş'in ışığı dünyaya kaç dakikada ulaşır?", c: "Yaklaşık 8 dakika", yanlislar: ["1 saat", "30 saniye", "1 gün"] },
    { s: "Ay'ın Dünya'ya bakan yüzü neden hep aynıdır?", c: "Kendi ekseni etrafındaki dönme süresi ile Dünya etrafındaki dönme süresi eşit olduğu için", yanlislar: ["Ay hiç dönmediği için", "Dünya Ay'ı durdurduğu için", "Ay sabit durduğu için"] },
    { s: "Geceleri yön bulmak için kullanılan Kutup Yıldızı hangi takımyıldızındadır?", c: "Küçük Ayı", yanlislar: ["Büyük Ayı", "Orion", "Ejderha"] },
    { s: "Samanyolu galaksisinin biçimi nasıldır?", c: "Sarmal (Spiral)", yanlislar: ["Küresel", "Kare", "Düzensiz"] },
    { s: "Samanyolu galaksisine en yakın büyük komşu galaksi hangisidir?", c: "Andromeda", yanlislar: ["Sombrero", "Üçgen", "Büyük Macellan"] },
    { s: "Evrendeki en güçlü çekim kuvvetine sahip nesneler nedir?", c: "Karadelik", yanlislar: ["Nötron yıldızı", "Beyaz cüce", "Kuyruklu yıldız"] },
    { s: "Bir yıldızın karadeliğe dönüşmesi için ne kadar kütleye sahip olması gerekir?", c: "Çok büyük dev kütlelere", yanlislar: ["Küçük kütlelere", "Dünya kadar kütleye", "Ay kadar kütleye"] },
    { s: "Uzaya çıkan ilk kadın astronot kimdir?", c: "Valentina Tereshkova", yanlislar: ["Sally Ride", "Mae Jemison", "Peggy Whitson"] },
    { s: "Ay'a ayak basan ikinci insan kimdir?", c: "Buzz Aldrin", yanlislar: ["Neil Armstrong", "Yuri Gagarin", "Michael Collins"] },
    { s: "Uzay yürüyüşünü gerçekleştiren ilk insan kimdir?", c: "Alexei Leonov", yanlislar: ["Yuri Gagarin", "Neil Armstrong", "John Glenn"] },
    { s: "Türkiye'nin uzaya giden ilk insanı kimdir?", c: "Alper Gezeravcı", yanlislar: ["Tuzcuoğlu", "Halil Kayıkçı", "Orhan Şen"] },
    { s: "Türkiye'nin ilk gözlem uydularından biri hangisidir?", c: "Göktürk veya Rasat", yanlislar: ["Sputnik", "Hubble", "Voyager"] },
    { s: "Uluslararası Uzay İstasyonu (ISS) hangi yılda hizmete girmiştir?", c: "1998", yanlislar: ["1969", "1981", "2010"] },
    { s: "Uzay araçlarının dünyaya dönerken yanmasını önleyen sisteme ne denir?", c: "Isı kalkanı", yanlislar: ["Soğutma kliması", "Su perdesi", "Rüzgar kesici"] },
    { s: "Mars'ın yüzeyinde su arayan ünlü NASA araçlarının genel adı nedir?", c: "Gezgin (Rover - Curiosity / Perseverance)", yanlislar: ["Uçak", "Sondaj", "Roket"] },
    { s: "Asteroit kuşağı hangi iki gezegen arasında yer alır?", c: "Mars ile Jüpiter", yanlislar: ["Dünya ile Mars", "Jüpiter ile Satürn", "Uranüs ile Neptün"] },
    { s: "Kuiper Kuşağı Güneş sisteminin neresinde yer alır?", c: "Neptün'ün ötesinde", yanlislar: ["Merkür'ün yanında", "Mars ile Jüpiter arasında", "Güneş'in merkezinde"] },
    { s: "Plüton'un bulunduğu uzak ve buzlu bölgenin adı nedir?", c: "Kuiper Kuşağı", yanlislar: ["Asteroit kuşağı", "Oort bulutu", "Van Allen kuşağı"] },
    { s: "Güneş sistemini çevreleyen en dıştaki buzlu cisimler bulutuna ne denir?", c: "Oort Bulutu", yanlislar: ["Kuiper Kuşağı", "Asteroit Kuşağı", "Nebula"] },
    { s: "Uzay çöpleri nedir?", c: "Dünya yörüngesindeki işlevsiz insan yapımı kalıntılar", yanlislar: ["Doğal göktaşları", "Yıldız tozları", "Kuyruklu yıldız parçaları"] },
    { s: "Güneş enerjisi hangi elementlerin birleşmesiyle oluşur?", c: "Hidrojenin Helyuma dönüşmesiyle", yanlislar: ["Demirin nikel olmasıyla", "Oksijenin yanmasıyla", "Karbonun erimesiyle"] },
    { s: "Güneş'in dünyaya olan en uzak noktasına ne denir?", c: "Günöte (Aphel)", yanlislar: ["Günberi", "Ekinoks", "Zirve"] },
    { s: "Güneş'in dünyaya en yakın olduğu noktaya ne denir?", c: "Günberi (Perihel)", yanlislar: ["Günöte", "Taban", "Solstice"] },
    { s: "Yıldızların gökyüzündeki günlük hareketinin temel sebebi nedir?", c: "Dünya'nın kendi ekseni etrafında dönmesi", yanlislar: ["Yıldızların hareket etmesi", "Ay'ın çekimi", "Güneş'in batması"] },
    { s: "Güneş sistemindeki en büyük volkanik dağ olan Olympus Mons kaç kilometredir?", c: "Yaklaşık 22 kilometre", yanlislar: ["5 kilometre", "10 kilometre", "50 kilometre"] },
    { s: "Dünya'nın uydusu Ay'ın yerçekimi Dünya'nınkine göre nasıldır?", c: "Çok daha azdır (yaklaşık altıda biri)", yanlislar: ["Daha fazladır", "Aynıdır", "Hiç yoktur"] },
    { s: "Ay yüzeyinde hava olmadığı için ne duyulamaz?", c: "Hiçbir ses", yanlislar: ["Rüzgar sesi", "Taş düşme sesi", "Gök gürültüsü"] },
    { s: "Güneş tutulması sırasında gökyüzü neden karartı gibi olur?", c: "Ay, Güneş'in önünü kapattığı için", yanlislar: ["Gece olduğu için", "Bulutlar kapattığı için", "Güneş söndüğü için"] },
    { s: "Ay tutulması hangi evrede meydana gelir?", c: "Dolunay", yanlislar: ["Yeni Ay", "Hilal", "İlk dördün"] },
    { s: "Güneş tutulması hangi evrede meydana gelir?", c: "Yeni Ay", yanlislar: ["Dolunay", "Son dördün", "Hilal"] },
    { s: "Uzayda astronotlar tuvalet ihtiyacını nasıl giderirler?", c: "Özel vakumlu özel tuvalet sistemleriyle", yanlislar: ["Normal tuvaletle", "Boşluğa bırakarak", "Alt bezleriyle"] },
    { s: "Uzayda su nasıl içilir?", c: "Özel pipetli kapalı torbalardan", yanlislar: ["Bardaktan dökerek", "Kaşıkla", "Havadan yalayarak"] },
    { s: "Güneş rüzgarları dünyaya çarptığında neyi etkiler?", c: "Dünya'nın manyetik alanını ve uyduları", yanlislar: ["Okyanus dalgalarını", "Dağları", "Toprak verimliliğini"] },
    { s: "Güneş sistemindeki en büyük manyetik alana sahip gezegen hangisidir?", c: "Jüpiter", yanlislar: ["Dünya", "Satürn", "Neptün"] },
    { s: "Venüs gezegeninin atmosferinde en çok hangi gaz bulunur?", c: "Karbondioksit", yanlislar: ["Oksijen", "Azot", "Hidrojen"] },
    { s: "Mars'ın atmosferi ağırlıklı olarak hangi gazdan oluşur?", c: "Karbondioksit", yanlislar: ["Helyum", "Oksijen", "Metan"] },
    { s: "Uranüs ve Neptün'ün mavimsi görünmesinin sebebi gazlarındaki hangi maddedir?", c: "Metan gazı", yanlislar: ["Su buharı", "Azot", "Karbondioksit"] },
    { s: "Dünya'nın manyetik kutupları coğrafi kutuplarla tam üst üste midir?", c: "Hayır, biraz kaymıştır", yanlislar: ["Evet, tamamen aynıdır", "Hiç alakası yoktur", "Sürekli yer değiştirirler"] },
    { s: "Pusulalar yönü bulurken neyi kullanır?", c: "Dünya'nın manyetik alanını", yanlislar: ["Güneş'in konumunu", "Kutup Yıldızı'nı", "Yıldız haritalarını"] },
    { s: "Gökbilimcilerin gök cisimlerinin tayfını inceleyerek neyi bulurlar?", c: "Hangi maddelerden oluştuğunu", yanlislar: ["Kaç yaşında olduklarını", "Kim tarafından yapıldıklarını", "Ağırlıklarını"] },
    { s: "Hangi uzay teleskobu uzaya gönderilen ilk büyük optik uzay teleskobudur?", c: "Hubble Uzay Teleskobu", yanlislar: ["James Webb", "Kepler", "Spitzer"] },
    { s: "Gezegenleri keşfetmek için kullanılan Kepler Teleskobu özellikle neyi arardı?", c: "Ötegezegenleri (Güneş sistemi dışındaki gezegenleri)", yanlislar: ["Karadelikleri", "Kuyruklu yıldızları", "Galaksileri"] },
    { s: "Dünya dışında başka bir gezegende yürüyen ilk insan yapımı araç hangi ülkeye aittir?", c: "Sovyetler Birliği (Lunokhod - Luna programı)", yanlislar: ["Amerika", "Çin", "Fransa"] },
    { s: "Ay'a ilk insan hangi yıl gerçekleşmiştir?", c: "1969", yanlislar: ["1957", "1975", "1981"] },
    { s: "Apollo 11 göreviyle Ay'a inen modülün adı neydi?", c: "Kartal (Eagle)", yanlislar: ["Kartal Gözü", "Apollo", "Sputnik"] },
    { s: "Uzay yarışını başlatan olay nedir?", c: "Sputnik 1'in fırlatılması", yanlislar: ["Ay'a gidilmesi", "Hubble'ın kurulması", "ISS'in yapılması"] },
    { s: "Yuri Gagarin uzaya çıktıktan sonra dünyaya nasıl döndü?", c: "Kapsülle paraşütle inerek", yanlislar: ["Uçak gibi inerek", "Roketle inerek", "Yürüyerek"] },
    { s: "Astronotların uzayda boyunun uzamasının sebebi nedir?", c: "Yerçekimi olmadığı için omurganın genleşmesi", yanlislar: ["Havanın az olması", "Spor yapmaları", "Yemek düzeni"] },
    { s: "Güneş sistemindeki en büyük kanyon olan Valles Marineris hangi gezegendedir?", c: "Mars", yanlislar: ["Dünya", "Venüs", "Merkür"] },
    { s: "Venüs'ün yüzeyinde basınç dünyadakine göre nasıldır?", c: "Çok daha fazladır (dünyanın katlarca katı)", yanlislar: ["Daha azdır", "Aynıdır", "Hiç yoktur"] },
    { s: "Merkür'de gece ve gündüz arasındaki sıcaklık farkı nasıldır?", c: "Aşırı derecede büyüktür", yanlislar: ["Hiç yok denecek kadar azdır", "Sabit kalır", "Her zaman aynıdır"] },
    { s: "Güneş sistemindeki en yüksek dağlar genellikle hangi tür gezegenlerde olur?", c: "Karasal (kayalık) gezegenlerde", yanlislar: ["Gaz devlerinde", "Buz devlerinde", "Cüce gezegenlerde"] },
    { s: "Gezegenlerin güneş etrafında dönerken izledikleri yörünge tam daire midir?", c: "Hayır, elips şeklindedir", yanlislar: ["Evet, mükemmel dairedir", "Karedir", "Düz çizgidir"] },
    { s: "Güneş sistemimiz Samanyolu galaksisinin merkezine ne kadar uzaktadır?", c: "Yaklaşık 26 bin ışık yılı", yanlislar: ["Tam merkezindedir", "100 ışık yılı", "1 milyon ışık yılı"] },
    { s: "Samanyolu galaksisinin şekli uzayda neye benzer?", c: "Dev bir fırıldak veya girdaba", yanlislar: ["Topaç gibi bir küreye", "Kutuya", "Çubuğa"] },
    { s: "Evrenin genişlediğini ilk kez gözlemlerle kanıtlayan ünlü bilim insanı kimdir?", c: "Edwin Hubble", yanlislar: ["Albert Einstein", "Isaac Newton", "Galileo Galilei"] },
    { s: "Büyük Patlama (Big Bang) teorisine göre evren ne zaman oluşmuştur?", c: "Yaklaşık 13.8 milyar yıl önce", yanlislar: ["4.5 milyar yıl önce", "100 bin yıl önce", "100 milyar yıl önce"] },
    { s: "Güneş sistemimizin yaşı yaklaşık olarak kadardır?", c: "4.6 milyar yıl", yanlislar: ["13.8 milyar yıl", "1 milyon yıl", "10 bin yıl"] },
    { s: "Güneş sisteminde yaşamın olması için gereken en temel sıvı nedir?", c: "Sıvı su", yanlislar: ["Sıvı metan", "Likit azot", "Sıvı hidrojen"] },
    { s: "Güneş sistemindeki hangi uydularda yeraltı okyanusları olduğu düşünülmektedir?", c: "Europa ve Enceladus", yanlislar: ["Phobos ve Deimos", "Ay ve Titan", "Hiçbirinde yoktur"] },
    { s: "Satürn'ün uydusu Enceladus'un güney kutbundan uzaya ne püskürür?", c: "Su buharı ve buz tanecikleri", yanlislar: ["Ateş ve lav", "Kömür tozu", "Metan gazı"] },
    { s: "Güneş sistemindeki en büyük kraterlerden biri olan Caloris Havzası hangi gezegendedir?", c: "Merkür", yanlislar: ["Ay", "Mars", "Venüs"] },
    { s: "Mars'ın iki rengi uzaydan bakıldığında ne olarak görünür?", c: "Kırmızı toprak ve beyaz kutup buzulları", yanlislar: ["Mavi okyanuslar", "Yeşil ormanlar", "Sarı çöller"] },
    { s: "Güneş sistemindeki en büyük gaz devi olan Jüpiter'in halkaları var mıdır?", c: "Evet, sönük halkaları vardır", yanlislar: ["Hayır, hiç yoktur", "Sadece Satürn'ün vardır", "Buzdan dev halkaları vardır"] },
    { s: "Uzay araçları gücünü çoğunlukla nereden alır?", c: "Güneş panellerinden", yanlislar: ["Rüzgar türbinlerinden", "Kömürden", "Nükleer pillerden"] },
    { s: "Ay'ın yüzeyindeki karanlık düzlüklere ne ad verilmiştir?", c: "Deniz (Maria)", yanlislar: ["Okyanus çukuru", "Vadi", "Krater"] },
    { s: "Güneş sisteminde uydusu olmayan tek karasal gezegenler hangileridir?", c: "Merkür ve Venüs", yanlislar: ["Sadece Merkür", "Sadece Venüs", "Dünya ve Mars"] },
    { s: "Uzayda astronotların yön duygusunu kaybetmesine ne sebep olur?", c: "Yerçekimsizlik", yanlislar: ["Karanlık olması", "Yıldızların çok olması", "Hızın fazla olması"] },
    { s: "Güneş sistemindeki en büyük asteroit ve ilk keşfedilen cüce gezegen hangisidir?", c: "Ceres", yanlislar: ["Plüton", "Eris", "Haumea"] },
    { s: "Dünya'nın atmosferi tabakalara ayrılır; içinde yaşadığımız en alt katmanın adı nedir?", c: "Troposfer", yanlislar: ["Stratosfer", "Mezosfer", "Termosfer"] },
    { s: "Güneş ışınlarının ozon tabakası sayesinde tutulduğu ve emildiği katman hangisidir?", c: "Stratosfer", yanlislar: ["Troposfer", "İyonosfer", "Exosfer"] },
    { s: "Kutup ışıklarının (Aurora) gerçekleştiği ve radyo dalgalarının yansıtıldığı atmosfer katmanı hangisidir?", c: "İyonosfer / Termosfer", yanlislar: ["Troposfer", "Stratosfer", "Ozon tabakası"] },
    { s: "Güneş sisteminde uydusu olmayan gezegenlerin ortak özelliği nedir?", c: "Güneş'e en yakın iki gezegen olmaları", yanlislar: ["En büyük gezegen olmaları", "Gaz devi olmaları", "Çok uzak olmaları"] },
    { s: "Mars'ın yüzeyinde bulunan ve suyun geçmişteki izlerini taşıyan minerallere ne denir?", c: "Kil ve sülfat mineralleri", yanlislar: ["Kömür tabakaları", "Elmas kristalleri", "Altın damarları"] },
    { s: "Uluslararası Uzay İstasyonu dünya etrafındaki bir turunu günde yaklaşık kaç kez tamamlar?", c: "Günde yaklaşık 15-16 kez", yanlislar: ["Günde 1 kez", "Günde 50 kez", "Ayda bir kez"] },
    { s: "Güneş sistemindeki en büyük yanardağ olan Olympus Mons hangi gezegenin hangi bölgesindedir?", c: "Tharsis volkanik bölgesinde", yanlislar: ["Kuzey kutbunda", "Ekvator çizgisinde", "Güney çukurunda"] },
    { s: "Jüpiter'in etrafındaki en içteki büyük uydulardan biri olan ve üzerinde yüzlerce aktif volkan bulunduran gök cismi hangisidir?", c: "Io", yanlislar: ["Europa", "Ganymede", "Callisto"] },
    { s: "Jüpiter'in en dışındaki büyük uydulardan biri olan, kraterlerle kaplı buzlu gök cismi hangisidir?", c: "Callisto", yanlislar: ["Io", "Titan", "Phobos"] },
    { s: "Satürn'ün halkaları ağırlıklı olarak hangi maddeden oluşur?", c: "Su buzu parçacıkları ve kayalardan", yanlislar: ["Saf demirden", "Köpükten", "Gaz bulutundan"] },
    { s: "Uranüs'ün renginin mavi-yeşil olmasının sebebi atmosferindeki yüksek oranda hangi gazdır?", c: "Metan gazı", yanlislar: ["Oksijen", "Karbondioksit", "Helyum"] },
    { s: "Neptün'ün en büyük uydusunun adı nedir?", c: "Triton", yanlislar: ["Titan", "Europa", "Ganymede"] },
    { s: "Neptün'ün uydusu Triton'un en büyük özelliklerinden biri nedir?", c: "Gezegenin dönme yönünün tersine hareket etmesi (retrograde)", yanlislar: ["Halkasının olmaması", "Çok sıcak olması", "Dünya'dan büyük olması"] },
    { s: "Plüton'un günde bir tur atma süresi (kendi ekseni etrafındaki dönme süresi) dünyada kaç saattir?", c: "Yaklaşık 153 saat (6 günden fazla)", yanlislar: ["24 saat", "48 saat", "12 saat"] },
    { s: "Güneş'in kütlesi tüm sistemin yüzde kaçını oluşturur?", c: "Yüzde 99.86", yanlislar: ["Yüzde 50", "Yüzde 80", "Yüzde 90"] },
    { s: "Güneş'in en dıştaki taç katmanına ne ad verilir?", c: "Korona", yanlislar: ["Fotosfer", "Kromosfer", "Çekirdek"] },
    { s: "Güneş'in görünür yüzeyine ne ad verilir?", c: "Fotosfer (Işık küre)", yanlislar: ["Korona", "Çekirdek", "Manto"] },
    { s: "Yıldızların doğduğu soğuk gaz ve toz bulutlarına genel olarak ne ad verilir?", c: "Moleküler bulut veya Nebula", yanlislar: ["Asteroid", "Meteor", "Kuasar"] },
    { s: "Kuasar nedir?", c: "Çok uzaklardaki devasa parlak aktif galaksi çekirdeği", yanlislar: ["Küçük bir uydu", "Kuyruklu yıldız türü", "Gezegen çeşidi"] },
    { s: "Pulsar nedir?", c: "Hızlı dönen ve düzenli radyo dalgaları yayan nötron yıldızı", yanlislar: ["Sönen bir yıldız", "Yeni doğan güneş", "Gaz bulutu"] },
    { s: "Kara deliklerin etrafında ışıktan başka hiçbir şeyin kaçamayacağı sınıra ne denir?", c: "Olay Ufkuna (Event Horizon)", yanlislar: ["Merkez noktası", "Işık sınırı", "Çekim duvarı"] },
    { s: "Einstein'ın teorisine göre kütleçekim dalgaları ilk kez ne zaman doğrudan gözlemlenmiştir?", c: "2015 yılında", yanlislar: ["1905 yılında", "1969 yılında", "2020 yılında"] },
    { s: "Evrenin yaşlanırken her yönde birbirinden uzaklaşmasını ilk kim matematiksel olarak modellemiştir?", c: "Georges Lemaître ve Edwin Hubble", yanlislar: ["Isaac Newton", "Galileo Galilei", "Johannes Kepler"] },
    { s: "Güneş sistemindeki en büyük vadilerden biri olan Valles Marineris hangi gezegendedir?", c: "Mars", yanlislar: ["Venüs", "Dünya", "Merkür"] },
    { s: "Dünya'nın kendi ekseni etrafındaki dönüş hızı ekvatorda saatte yaklaşık kaç kilometredir?", c: "Yaklaşık 1670 kilometre", yanlislar: ["100 kilometre", "5000 kilometre", "300 kilometre"] },
    { s: "Dünya'nın Güneş etrafındaki yörüngesinde hareket ederken hızı saniyede ortalama kaç kilometredir?", c: "Saniyede yaklaşık 30 kilometre", yanlislar: ["Saniyede 1 kilometre", "Saniyede 300 kilometre", "Saniyede 5 kilometre"] },
    { s: "Ay tutulması sırasında Ay tam olarak hangi renge bürünebilir?", c: "Kızıl veya bakır rengine (Kanlı Ay)", yanlislar: ["Masmavi renge", "Bembeyaz renge", "Yeşil renge"] },
    { s: "Güneş tutulması sırasında görülen ve Güneş'in etrafındaki parıltılı tabaka nedir?", c: "Güneş koronası", yanlislar: ["Yıldızlar", "Ay'ın atmosferi", "Dünya'nın gölgesi"] },
    { s: "Hangi uzay aracı Güneş sisteminin dışına (yıldızlararası uzaya) çıkan ilk insan yapımı nesnedir?", c: "Voyager 1", yanlislar: ["Apollo 11", "Hubble", "Sputnik"] },
    { s: "Voyager 1 ve Voyager 2 uzay araçları hangi yıl fırlatılmıştır?", c: "1977", yanlislar: ["1969", "1985", "1990"] },
    { s: "Güneş sistemindeki en büyük dağ olan Olympus Mons bir ne tür dağdır?", c: "Kalkan volkan", yanlislar: ["Kıvrım dağ", "Fay dağı", "Çökel dağ"] },
    { s: "Venüs gezegeninin yüzeyinde sülfürik asit bulutlarının olmasının sebebi nedir?", c: "Yoğun volkanik faaliyetler ve gazlar", yanlislar: ["Okyanusların buharlaşması", "Güneş'e çok yakın olması", "Uydusunun olmaması"] },
    { s: "Merkür'ün yüzeyindeki sıcaklık güneş gören tarafta kaç dereceye kadar çıkabilir?", c: "430 derece civarı", yanlislar: ["100 derece", "1000 derece", "50 derece"] },
    { s: "Merkür'ün güneş görmeyen karanlık yüzündeki sıcaklık kaça kadar düşebilir?", c: "Eksi 180 derece civarı", yanlislar: ["Sıfır derece", "Eksi 10 derece", "Eksi 50 derece"] },
    { s: "Güneş sistemindeki gezegenler içinde kendi etrafında en yavaş dönen hangisidir?", c: "Venüs", yanlislar: ["Jüpiter", "Merkür", "Mars"] },
    { s: "Dünya'nın manyetik alanı olmasaydı ne olurdu?", c: "Güneş rüzgarları atmosferi süpürür ve yaşam yok olurdu", yanlislar: ["Hiçbir şey değişmezdi", "Sadece pusulalar çalışmazdı", "Yıl süresi uzardı"] },
    { s: "Ay'ın yüzeyindeki toz tabakasına ne ad verilir?", c: "Regolit", yanlislar: ["Toprak", "Kil", "Kömür"] },
    { s: "Gökbilimciler uzaydaki uzaklıkları ölçerken paralaks yöntemini ne için kullanırlar?", c: "Yakın yıldızların mesafesini ölçmek için", yanlislar: ["Karadelikleri bulmak için", "Galaksilerin hızını ölçmek için", "Gezegenlerin ağırlığını bulmak için"] },
    { s: "Yıldızların parlaklığını belirleyen mutlak kadir nedir?", c: "Yıldızın standart bir uzaklıktaki gerçek parlaklığı", yanlislar: ["Dünyadan görülen parlaklığı", "Yıldızın büyüklüğü", "Sıcaklık derecesi"] },
    { s: "Güneş sisteminin galaksi merkezi etrafındaki bir tam turu (Galaktik yıl) ne kadar sürer?", c: "Yaklaşık 225-250 milyon yıl", yanlislar: ["1 milyon yıl", "10 bin yıl", "5 milyar yıl"] },
    { s: "Aşağıdakilerden hangisi bir takımyıldız değildir?", c: "Samanyolu", yanlislar: ["Büyük Ayı", "Orion", "Kutup"] },
    { s: "Güneş sistemindeki en büyük asteroitlerden biri olan Vesta nerede bulunur?", c: "Asteroit Kuşağı'nda", yanlislar: ["Kuiper Kuşağı'nda", "Oort Bulutu'nda", "Mars'ın yüzeyinde"] },
    { s: "Güneş lekesi döngüsü ortalama kaç yılda bir tekrarlanır?", c: "11 yılda bir", yanlislar: ["1 yılda bir", "50 yılda bir", "100 yılda bir"] },
    { s: "Uluslararası Uzay İstasyonu'nda görev yapan astronotlar günde kaç kez gündüz ve gece yaşarlar?", c: "16 kez", yanlislar: ["1 kez", "4 kez", "Gündüz hiç olmaz"] },
    { s: "Uzaydaki ilk uzay istasyonu hangisidir?", c: "Salyut 1 (SSCB)", yanlislar: ["Mir", "Skylab", "ISS"] },
    { s: "Rusya'nın uzun süre uzayda kalan ve okyanusa düşürülen ünlü uzay istasyonunun adı nedir?", c: "Mir", yanlislar: ["Salyut", "Skylab", "Challenger"] },
    { s: "Amerika'nın ilk tek başına kurduğu uzay istasyonunun adı nedir?", c: "Skylab", yanlislar: ["Mir", "Salyut", "Discovery"] },
    { s: "Uzay mekiklerinden ilki olan ve fırlatılan araç hangisidir?", c: "Columbia", yanlislar: ["Challenger", "Discovery", "Atlantis"] },
    { s: "Astronotların uzay boşluğunda çalışırken giydiği tam korumalı kıyafetin uluslararası adı nedir?", c: "EMU (Extravehicular Mobility Unit)", yanlislar: ["Spacesuit-X", "Apollo-Tulum", "Cosmo-Gear"] },
    { s: "Güneş sistemindeki en büyük volkanik dağ olan Olympus Mons'un tabanı ne kadardır?", c: "Türkiye'nin yüz ölçümü kadar", yanlislar: ["Küçük bir dağ kadardır", "İstanbul kadardır", "Bir mahalle büyüklüğündedir"] },
    { s: "Mars'ın kırmızı görünümüne sebep olan demir oksit tozu kalınlığı nasıldır?", c: "Yüzeyi kaplayan ince bir toz katmanıdır", yanlislar: ["Kilometrelerce kalınlıktadır", "Taş kütlesidir", "Sıvı haldedir"] },
    { s: "Jüpiter'in uydusu Europa'nın buz kabuğunun altında ne kadar kalınlıkta okyanus olabileceği tahmin edilir?", c: "Onlarca kilometre kalınlığında", yanlislar: ["Sadece birkaç metre", "1 kilometre", "Hiç su yoktur"] },
    { s: "Satürn'ün uydusu Titan'ın yüzeyinde ne tür hava olayları görülür?", c: "Metan yağan yağmurlar ve göller", yanlislar: ["Su yağmurları ve denizler", "Kum fırtınaları", "Lav yağmurları"] },
    { s: "Uranüs'ün uydularının isimleri genellikle kimlerin eserlerinden alınmıştır?", c: "William Shakespeare ve Alexander Pope'un karakterlerinden", yanlislar: ["Yunan tanrılarından", "Roma imparatorlarından", "Ünlü bilim insanlarından"] },
    { s: "Neptün'ün en belirgin özelliklerinden biri olan fırtınanın adı nedir?", c: "Büyük Karanlık Leke", yanlislar: ["Kırmızı Göz", "Mavi Fırtına", "Büyük Girdap"] },
    { s: "Plüton'un kalbe benzeyen devasa buz ovasının resmi adı nedir?", c: "Tombaugh Regio", yanlislar: ["Sagan Ovası", "Armstrong Bölgesi", "Galileo Çukuru"] },
    { s: "Güneş sisteminde Güneş'e en yakın cüce gezegen hangisidir?", c: "Ceres", yanlislar: ["Plüton", "Haumea", "Eris"] },
    { s: "Güneş sistemindeki en uzak bilinen büyük cüce gezegenlerden biri hangisidir?", c: "Eris", yanlislar: ["Ceres", "Makemake", "Sedna"] },
    { s: "Gökbilimciler yeni bir gezegen veya asteroit bulduklarında konumu neye göre belirlerler?", c: "Gökküre üzerindeki koordinat sistemine (sağ açıklık ve dik açıklık)", yanlislar: ["Dünya'daki saatlere", "GPS uydularına", "Yıldızların sıcaklığına"] },
    { s: "Yıldızların tayf türleri harflerle sınıflandırılır; en sıcak olan O'dan en soğuk olana doğru sıralamanın son harfi nedir?", c: "M sınıfı", yanlislar: ["Z sınıfı", "X sınıfı", "K sınıfı"] },
    { s: "Güneş'imiz tayf sınıflamasına göre hangi harf grubundadır?", c: "G sınıfı", yanlislar: ["O sınıfı", "M sınıfı", "B sınıfı"] },
    { s: "Aşağıdakilerden hangisi bir takımyıldız değil, bir galaksidir?", c: "Andromeda", yanlislar: ["Büyük Ayı", "Orion", "Kutup"] },
    { s: "Samanyolu galaksisinin merkezinde hangi yönde yer alırız?", c: "Yay (Sagittarius) takımyıldızı yönünde", yanlislar: ["Büyük Ayı yönünde", "Kutup Yıldızı yönünde", "Orion yönünde"] },
    { s: "Güneş sistemindeki en büyük ikinci uydu hangisidir?", c: "Titan (Satürn'ün uydusu)", yanlislar: ["Europa", "Io", "Callisto"] },
    { s: "Ay'ın yüzeyinde su buzunun ilk kesin kanıtları nerede bulunmuştur?", c: "Kutup bölgelerindeki gölgede kalmış kraterlerde", yanlislar: ["Ekvator bölgesinde", "Kraterlerin tepesinde", "Deniz düzlüklerinde"] },
    { s: "Güneş'in kütleçekimi gezegenleri yörüngede tutarken, gezegenler neden güneşe düşmezler?", c: "Sahip oldukları yörünge hızı ve merkezkaç dengesi sayesinde", yanlislar: ["Güneş onları iter", "Uzayda yerçekimi yoktur", "Aralarında duvar vardır"] },
    { s: "Uzay araçları başka gezegenlerin çekim gücünü kullanarak hız kazanma yöntemine ne denir?", c: "Kütleçekim sapanı etkisi (Gravity assist)", yanlislar: ["Roket itmesi", "Rüzgar gücü", "Manyetik çekim"] },
    { s: "Voyager uzay araçları hangi gezegenlerin yakınından geçerek dış sisteme ulaşmıştır?", c: "Jüpiter, Satürn, Uranüs ve Neptün", yanlislar: ["Sadece Mars ve Venüs", "Sadece Merkür", "Plüton ve Güneş"] },
    { s: "Güneş sistemindeki en büyük manyetik alana sahip gezegen olan Jüpiter'in manyetosferi ne kadar büyüktür?", c: "Dünyadan bile büyüktür, güneşten büyük yer kaplar", yanlislar: ["Sadece gezegeni sarar", "Çok küçüktür", "Hiç yoktur"] },
    { s: "Mars'ın uyduları şekil olarak neye benzerler?", c: "Patates benzeri düzensiz kaya parçalarına", yanlislar: ["Mükemmel kürelere", "Halkalara", "Parlak disklere"] },
    { s: "Venüs'ün kendi etrafındaki dönüş süresi (bir günü) Güneş etrafındaki dönüş süresinden (bir yılından) nasıldır?", c: "Daha uzundur", yanlislar: ["Daha kısadır", "Eşittir", "Kıyaslanamaz"] },
    { s: "Merkür'ün etrafında bir atmosfer olmamasının sebebi nedir?", c: "Kütleçekiminin çok zayıf olması ve güneş rüzgarları", yanlislar: ["Güneş'e çok uzak olması", "Çok soğuk olması", "Su olmaması"] },
    { s: "Dünya'nın uydusu Ay'ın yaşının yaklaşık kaç yıl olduğu tahmin edilmektedir?", c: "Yaklaşık 4.5 milyar yıl", yanlislar: ["10 bin yıl", "100 milyon yıl", "10 milyar yıl"] },
    { s: "Güneş sistemindeki en büyük çarpışma kraterlerinden biri olan Caloris Havzası hangi gök cismindedir?", c: "Merkür", yanlislar: ["Ay", "Mars", "Venüs"] },
    { s: "Dünya'nın eksen eğikliği tam olarak kaç derecedir?", c: "23.44 derece", yanlislar: ["0 derece", "45 derece", "90 derece"] },
    { s: "Güneş sisteminde mevsimleri olan ve eksen eğikliği dünyaya en çok benzeyen gezegen hangisidir?", c: "Mars", yanlislar: ["Jüpiter", "Merkür", "Venüs"] },
    { s: "Uranüs'ün uydularının adları Shakespeare karakterleri dışında kimlerin adını taşır?", c: "Alexander Pope'un şiirlerindeki karakterlerin", yanlislar: ["Yunan tanrılarının", "Astronotların", "Yazarların"] },
    { s: "Neptün'ün atmosferindeki en hızlı rüzgarlar saatte kaç kilometreye ulaşır?", c: "2000 kilometreden fazla", yanlislar: ["100 kilometre", "500 kilometre", "1000 kilometre"] },
    { s: "Plüton'un keşfi hangi yıl ve kim tarafından gerçekleştirilmiştir?", c: "1930 yılında Clyde Tombaugh tarafından", yanlislar: ["1609 yılında Galileo tarafından", "1969 yılında Armstrong tarafından", "1905 yılında Einstein tarafından"] },
    { s: "Güneş sistemindeki asteroit kuşağında bulunan en büyük cisim (ve cüce gezegen) hangisidir?", c: "Ceres", yanlislar: ["Vesta", "Pallas", "Hygiea"] },
    { s: "Güneş sisteminde kuyruklu yıldızların kaynağı olarak bilinen iki ana bölge hangileridir?", c: "Kuiper Kuşağı ve Oort Bulutu", yanlislar: ["Asteroit kuşağı ve Mars", "Merkür ve Venüs", "Dünya ve Ay"] },
    { s: "Evrenin en bol bulunan ikinci elementi hangisidir?", c: "Helyum", yanlislar: ["Oksijen", "Karbon", "Azot"] },
    { s: "Yıldızların merkezindeki nükleer füzyon hangi elementin tükenmesiyle son evresine girer?", c: "Hidrojen", yanlislar: ["Demir", "Helyum", "Karbon"] },
    { s: "Yıldızların evriminde demir elementinin üretilmesi neyin işaretidir?", c: "Yıldızın ömrünün sonuna geldiğinin (süpernova patlamasının)", yanlislar: ["Yıldızın yeni doğduğunun", "Yıldızın küçüldüğünün", "Yıldızın maviye döndüğünün"] },
    { s: "Güneş'in gelecekte dönüşeceği son kararlı küçük cisim ne olacaktır?", c: "Beyaz cüce", yanlislar: ["Karadelik", "Nötron yıldızı", "Süpernova"] },
    { s: "Güneş'ten çok daha büyük dev yıldızların çökmesiyle oluşan yoğun cisim nedir?", c: "Nötron yıldızı veya Karadelik", yanlislar: ["Sarı cüce", "Gezegen", "Kuyruklu yıldız"] },
    { s: "Galaksilerin birbirinden uzaklaşma hızının mesafeleriyle doğru orantılı olduğunu gösteren yasanın adı nedir?", c: "Hubble Yasası", yanlislar: ["Newton Kanunu", "Kepler Yasası", "Einstein Teorisi"] },
    { s: "Kozmik mikrodalga arka plan ışıması (CMB) neyin kanıtıdır?", c: "Büyük Patlama'nın (Big Bang) kalıntısı olduğunun", yanlislar: ["Güneş'in ısısının", "Yıldız kaymalarının", "Ay'ın evrelerinin"] },
    { s: "Güneş sistemi Samanyolu galaksisinin merkezinden ne kadar sürede bir geçer?", c: "Galaktik yıl (yaklaşık 230 milyon yılda bir)", yanlislar: ["365 günde bir", "100 yılda bir", "1 milyon yılda bir"] },
    { s: "Uluslararası Uzay İstasyonu'nun yapımına hangi yıl başlanmıştır?", c: "1998", yanlislar: ["1980", "1990", "2005"] },
    { s: "Uzay istasyonunda astronotlar su ihtiyacını karşılamak için neleri geri dönüştürürler?", c: "Kendi terlerini ve idrarlarını", yanlislar: ["Havadaki nemi", "Yağmur suyunu", "Bitki sularını"] },
    { s: "Uzayda yerçekimsiz ortamda omurga esnemesi nedeniyle astronotların boyu ne kadar uzayabilir?", c: "Birkaç santimetre (yaklaşık 5 cm)", yanlislar: ["Y yarı yarıya uzar", "Hiç değişmez", "1 metre uzar"] },
    { s: "Ay yüzeyindeki sıcaklık güneş altındayken kaça kadar çıkabilir?", c: "120 derece civarı", yanlislar: ["500 derece", "50 derece", "10 derece"] },
    { s: "Ay yüzeyindeki sıcaklık gece karanlığında kaça kadar düşebilir?", c: "Eksi 130 derece civarı", yanlislar: ["Eksi 10 derece", "Sıfır", "Eksi 273 derece"] },
    { s: "Güneş sistemindeki en büyük yanardağ olan Olympus Mons dünyadaki hangi dağdan kaç kat daha yüksektir?", c: "Everest'ten yaklaşık 3 kat daha yüksektir", yanlislar: ["Aynı boydadır", "Yarım kat yüksektir", "10 kat yüksektir"] },
    { s: "Mars'ın iki uydusunun adları hangi mitolojik karakterlerden gelmektedir?", c: "Yunan mitolojisindeki Savaş tanrısının çocukları Korku ve Dehşet'ten", yanlislar: ["Gezegen isimlerinden", "Ünlü krallardan", "Yıldız adlarından"] },
    { s: "Jüpiter'in uydusu Europa'nın yüzeyi neyle kaplıdır?", c: "Kalın bir su buzu tabakasıyla", yanlislar: ["Saf demirle", "Kaya parçalarıyla", "Kuru toprakla"] },
    { s: "Satürn'ün uydusu Titan'ın atmosferi dünyadakine benzer şekilde ağırlıklı olarak hangi gazdan oluşur?", c: "Azot (Nitrojen)", yanlislar: ["Oksijen", "Karbondioksit", "Helyum"] },
    { s: "Güneş'e en uzak gaz devi gezegen hangisidir?", c: "Neptün", yanlislar: ["Uranüs", "Satürn", "Jüpiter"] },
    { s: "Uranüs'ün güneşe olan uzaklığı dünyadakinin yaklaşık kaç katıdır?", c: "Yaklaşık 19 katı", yanlislar: ["2 katı", "5 katı", "100 katı"] },
    { s: "Güneş sistemindeki en büyük asteroit kuşağı hangi iki gezegen arasında yer alır?", c: "Mars ile Jüpiter", yanlislar: ["Dünya ile Mars", "Satürn ile Uranüs", "Venüs ile Dünya"] },
    { s: "Güneş sisteminin en dışında bulunan ve buzlu gök cisimlerinin oluşturduğu bölgeye ne ad verilir?", c: "Kuiper Kuşağı", yanlislar: ["Asteroit Kuşağı", "Oort Bulutu", "Manyetik Kuşak"] },
    { s: "Evrendeki en yaygın element hangisidir?", c: "Hidrojen", yanlislar: ["Oksijen", "Demir", "Karbon"] },
    { s: "Yıldızların doğduğu gaz ve toz bulutlarına ne denir?", c: "Nebula", yanlislar: ["Pulsar", "Kuasar", "Meteor"] },
    { s: "Dünya'nın uydusu Ay'ın yüzeyindeki karanlık düzlüklere ne ad verilir?", c: "Maria (Deniz)", yanlislar: ["Krater", "Vadi", "Çöl"] },
    { s: "Uranüs'ün diğer gezegenlerden farklı olarak dönme ekseni neredeyse ne kadar eğiktir?", c: "98 derece (yan yatmıştır)", yanlislar: ["23 derece", "0 derece", "45 derece"] },
    { s: "Gök cisimlerini inceleyen bilim dalına ne denir?", c: "Astronomi", yanlislar: ["Biyoloji", "Jeoloji", "Fizik"] },
    { s: "James Webb Uzay Teleskobu temel olarak hangi dalga boyunda gözlem yapar?", c: "Kızılötesi", yanlislar: ["Morötesi", "X-ışını", "Radyo dalgası"] },
    { s: "Yeryüzüne düşen göktaşı parçalarına ne denir?", c: "Meteorit", yanlislar: ["Meteor", "Nebula", "Asteroit"] },
    { s: "Güneş sistemindeki buz devi gezegenler hangileridir?", c: "Uranüs ve Neptün", yanlislar: ["Jüpiter ve Satürn", "Merkür ve Venüs", "Dünya ve Mars"] }
];