const ortaSorular = [
    { s: "Güneş sistemindeki en büyük volkanik dağ olan Olympus Mons hangi gezegendedir?", c: "Mars", yanlislar: ["Venüs", "Dünya", "Merkür"] },
    { s: "Venüs'ün atmosferi yoğun olarak hangi gazdan oluşur?", c: "Karbondioksit", yanlislar: ["Oksijen", "Azot", "Hidrojen"] },
    { s: "Güneş sistemindeki en soğuk gezegen hangisidir?", c: "Uranüs", yanlislar: ["Neptün", "Satürn", "Merkür"] },
    { s: "Güneş sistemindeki en hızlı esen rüzgarlar hangi gezegendedir?", c: "Neptün", yanlislar: ["Jüpiter", "Mars", "Venüs"] },
    { s: "Ay'ın Dünya etrafındaki bir turu yaklaşık kaç günde tamamlanır?", c: "27.3 gün", yanlislar: ["7 gün", "365 gün", "1 gün"] },
    { s: "Güneş tutulması hangi evrede gerçekleşir?", c: "Yeni Ay", yanlislar: ["Dolunay", "İlk dördün", "Son dördün"] },
    { s: "Ay tutulması hangi evrede gerçekleşir?", c: "Dolunay", yanlislar: ["Yeni Ay", "Hilal", "İlk dördün"] },
    { s: "Uzaya çıkan ilk insan kimdir?", c: "Yuri Gagarin", yanlislar: ["Neil Armstrong", "Buzz Aldrin", "Alper Gezeravcı"] },
    { s: "Ay'a ilk ayak basan insan kimdir?", c: "Neil Armstrong", yanlislar: ["Yuri Gagarin", "Michael Collins", "John Glenn"] },
    { s: "Türkiye'nin uzaya giden ilk insanı kimdir?", c: "Alper Gezeravcı", yanlislar: ["Tuzcuoğlu", "Halil Kayıkçı", "Orhan Şen"] },
    { s: "James Webb Uzay Teleskobu temel olarak hangi dalga boyunda gözlem yapar?", c: "Kızılötesi", yanlislar: ["Morötesi", "X-ışını", "Radyo dalgası"] },
    { s: "Güneş'in yüzey sıcaklığı yaklaşık kaç derecedir?", c: "5.500 derece", yanlislar: ["100 derece", "1 milyon derece", "500 derece"] },
    { s: "Yıldızların ömrünün sonbaharında devasa bir patlama ile parlamasına ne denir?", c: "Süpernova", yanlislar: ["Nebula", "Pulsar", "Asteroit"] },
    { s: "Işık hızı saniyede yaklaşık kaç kilometredir?", c: "300.000 kilometre", yanlislar: ["3.000 kilometre", "30 kilometre", "3 milyon kilometre"] },
    { s: "Güneş'e en yakın yıldızın adı nedir?", c: "Proxima Centauri", yanlislar: ["Sirius", "Betelgeuse", "Polaris"] },
    { s: "Geceleri yön bulmamıza yarayan Kutup Yıldızı hangi takımyıldızındadır?", c: "Küçük Ayı", yanlislar: ["Büyük Ayı", "Orion", "Ejderha"] },
    { s: "Gökyüzünde avcı olarak bilinen ünlü takımyıldız hangisidir?", c: "Orion", yanlislar: ["Kutup", "Yılan", "Kuğu"] },
    { s: "Samanyolu galaksisi ne tür bir galaksidir?", c: "Sarmal (Spiral)", yanlislar: ["Eliptik", "Düzensiz", "Kresel"] },
    { s: "Samanyolu'na en yakın büyük galaksi hangisidir?", c: "Andromeda", yanlislar: ["Sombrero", "Üçgen", "Magellan"] },
    { s: "Evrendeki her şeyi yutan ve güçlü çekime sahip yapı nedir?", c: "Karadelik", yanlislar: ["Nötron yıldızı", "Beyaz cüce", "Kuyruklu yıldız"] },
    { s: "Güneş sistemindeki en büyük uydunun adı nedir?", c: "Ganymede", yanlislar: ["Titan", "Europa", "Ay"] },
    { s: "Satürn'ün en büyük uydusunun adı nedir?", c: "Titan", yanlislar: ["Phobos", "Deimos", "Io"] },
    { s: "Mars'ın iki uydusundan biri Phobos'tur, diğeri hangisidir?", c: "Deimos", yanlislar: ["Europa", "Titan", "Callisto"] },
    { s: "Güneş sisteminde uydusu olmayan gezegenler hangileridir?", c: "Merkür ve Venüs", yanlislar: ["Dünya ve Mars", "Uranüs ve Neptün", "Jüpiter ve Satürn"] },
    { s: "Mars'ın kırmızı görünmesinin sebebi nedir?", c: "Yüzeyindeki demir oksit (pas) tozu", yanlislar: ["Su olmaması", "Çok sıcak olması", "Volkanlar"] },
    { s: "Jüpiter'in üzerindeki ünlü dev fırtınanın adı nedir?", c: "Büyük Kırmızı Leke", yanlislar: ["Mavi Girdap", "Siyah Nokta", "Beyaz Fırtına"] },
    { s: "Halley Kuyruklu Yıldızı dünyamızın yakınından ortalama kaç yılda bir geçer?", c: "75-76 yılda bir", yanlislar: ["10 yılda bir", "100 yılda bir", "1000 yılda bir"] },
    { s: "Uluslararası Uzay İstasyonu'nun kısaltılmış adı nedir?", c: "ISS", yanlislar: ["NASA", "ESA", "SPUTNIK"] },
    { s: "Uzay istasyonunda yerçekimi olmamasının sebebi nedir?", c: "Sürekli serbest düşme yörüngesinde olması", yanlislar: ["Havanın olmaması", "Çok uzak olması", "Güneş'in itmesi"] },
    { s: "Uzaya fırlatılan ilk yapay uydu hangisidir?", c: "Sputnik 1", yanlislar: ["Apollo 11", "Hubble", "Voyager 1"] },
    { s: "Güneş enerjisi hangi nükleer süreçle üretilir?", c: "Füzyon (birleşme)", yanlislar: ["Fisyon (bölünme)", "Yanma", "Paslanma"] },
    { s: "Güneş'in kütlesi tüm sistemin yaklaşık yüzde kaçını oluşturur?", c: "Yüzde 99.86", yanlislar: ["Yüzde 50", "Yüzde 80", "Yüzde 95"] },
    { s: "Güneş'in en dış katmanına ne ad verilir?", c: "Korona", yanlislar: ["Fotosfer", "Çekirdek", "Manto"] },
    { s: "Güneş'in leke döngüsü ortalama kaç yıldır?", c: "11 yıl", yanlislar: ["1 yıl", "50 yıl", "100 yıl"] },
    { s: "Güneş sistemindeki karasal gezegenler hangileridir?", c: "Merkür, Venüs, Dünya, Mars", yanlislar: ["Jüpiter, Satürn, Uranüs, Neptün", "Plüton, Ay, Güneş", "Satürn, Mars, Dünya"] },
    { s: "Güneş sistemindeki gaz devi gezegenler hangileridir?", c: "Jüpiter ve Satürn", yanlislar: ["Merkür ve Venüs", "Uranüs ve Neptün", "Dünya ve Mars"] },
    { s: "Güneş sistemindeki buz devi gezegenler hangileridir?", c: "Uranüs ve Neptün", yanlislar: ["Jüpiter ve Satürn", "Merkür ve Venüs", "Dünya ve Mars"] },
    { s: "Dünya'nın şekli bilimsel olarak nasıl tanımlanır?", c: "Geoid (Kutuplardan basık)", yanlislar: ["Tam daire", "Küp", "Düz tepsi"] },
    { s: "Dünya'nın eksen eğikliği yaklaşık kaç derecedir?", c: "23.5 derece", yanlislar: ["0 derece", "45 derece", "90 derece"] },
    { s: "Mevsimlerin oluşmasının temel sebebi nedir?", c: "Dünya'nın eksen eğikliği ve Güneş etrafındaki dönüşü", yanlislar: ["Dünya'nın kendi etrafındaki dönüşü", "Ay'ın çekimi", "Güneş'in ısınması"] },
    { s: "Gece ve gündüzün oluşmasının temel sebebi nedir?", c: "Dünya'nın kendi ekseni etrafında dönmesi", yanlislar: ["Dünya'nın Güneş etrafında dönmesi", "Ay'ın evreleri", "Mevsimler"] },
    { s: "Uzay boşluğunda ses neden yayılmaz?", c: "Ses dalgalarının yayılacağı hava ortamı olmadığı için", yanlislar: ["Çok soğuk olduğu için", "Yıldızlar uzak olduğu için", "Yerçekimi olmadığı için"] },
    { s: "Gökbilimde uzaklık ölçmek için kullanılan birim nedir?", c: "Işık yılı", yanlislar: ["Kilometre saati", "Metre", "Mil"] },
    { s: "Evrenin genişlediğini kanıtlayan ünlü yasa kime aittir?", c: "Edwin Hubble", yanlislar: ["Albert Einstein", "Isaac Newton", "Galileo Galilei"] },
    { s: "Büyük Patlama teorisine göre evren yaklaşık kaç yıl önce oluşmuştur?", c: "13.8 milyar yıl önce", yanlislar: ["4.5 milyar yıl önce", "100 bin yıl önce", "100 milyar yıl önce"] },
    { s: "Güneş sistemimizin yaşı yaklaşık kadardır?", c: "4.6 milyar yıl", yanlislar: ["13.8 milyar yıl", "1 milyon yıl", "10 bin yıl"] },
    { s: "Uzaya çıkan ilk kadın astronot kimdir?", c: "Valentina Tereshkova", yanlislar: ["Sally Ride", "Mae Jemison", "Peggy Whitson"] },
    { s: "Ay'a ayak basan ikinci insan kimdir?", c: "Buzz Aldrin", yanlislar: ["Neil Armstrong", "Michael Collins", "Yuri Gagarin"] },
    { s: "Uzay yürüyüşünü gerçekleştiren ilk insan kimdir?", c: "Alexei Leonov", yanlislar: ["Yuri Gagarin", "Neil Armstrong", "John Glenn"] },
    { s: "Güneş sistemindeki en büyük cüce gezegen hangisidir?", c: "Plüton", yanlislar: ["Ceres", "Eris", "Haumea"] },
    { s: "Asteroit kuşağında yer alan ilk keşfedilen cüce gezegen hangisidir?", c: "Ceres", yanlislar: ["Plüton", "Haumea", "Eris"] },
    { s: "Neptün'ün ötesindeki buzlu cisimlerin bulunduğu kuşağın adı nedir?", c: "Kuiper Kuşağı", yanlislar: ["Asteroit kuşağı", "Oort Bulutu", "Van Allen kuşağı"] },
    { s: "Güneş sistemini çevreleyen en dış bulut katmanına ne denir?", c: "Oort Bulutu", yanlislar: ["Kuiper Kuşağı", "Asteroit kuşağı", "Nebula"] },
    { s: "Uzay çöpleri nedir?", c: "Dünya yörüngesindeki işlevsiz insan yapımı kalıntılar", yanlislar: ["Doğal göktaşları", "Yıldız tozları", "Kuyruklu yıldız parçaları"] },
    { s: "Pusulalar yönü bulurken neyi baz alır?", c: "Dünya'nın manyetik alanını", yanlislar: ["Güneş'in konumunu", "Kutup Yıldızı'nı", "Yıldız haritalarını"] },
    { s: "Dünya'nın manyetik alanı bizi öncelikli olarak neyden korur?", c: "Güneş'ten gelen zararlı yüklü parçacıklardan (rüzgarlardan)", yanlislar: ["Göktaşlarından", "Ufolardan", "Ay'ın çekiminden"] },
    { s: "Kutup bölgelerinde görülen renkli ışık olayına ne denir?", c: "Aurora (Kutup Işıkları)", yanlislar: ["Şimşek", "Gökkuşağı", "Yıldız kayması"] },
    { s: "Güneş rüzgarları dünyaya çarptığında ağırlıklı olarak nereye yönlendirilir?", c: "Manyetik kutuplara", yanlislar: ["Ekvatora", "Okyanuslara", "Dağlara"] },
    { s: "Jüpiter'in uydusu Europa'da ne olduğu düşünülmektedir?", c: "Kalın buz tabakasının altında sıvı okyanus", yanlislar: ["Aktif yanardağlar", "Kuru çöl toprakları", "Devasa ormanlar"] },
    { s: "Satürn'ün uydusu Titan'ın yüzeyinde ne bulunur?", c: "Metan gölleri ve nehirleri", yanlislar: ["Su denizleri", "Lav nehirleri", "Kumlu çöller"] },
    { s: "Jüpiter'in uydusu Io neyle ün salmıştır?", c: "Yüzlerce aktif volkanıyla", yanlislar: ["Buzullarıyla", "Okyanuslarıyla", "Halkalarıyla"] },
    { s: "Neptün'ün en büyük uydusunun adı nedir?", c: "Triton", yanlislar: ["Titan", "Europa", "Ganymede"] },
    { s: "Uranüs'ün uydularına isimleri kimlerden ilham alınarak verilmiştir?", c: "William Shakespeare ve Alexander Pope karakterlerinden", yanlislar: ["Yunan tanrılarından", "Astronotlardan", "Bilim insanlarından"] },
    { s: "Güneş sistemindeki en büyük kanyon hangisidir?", c: "Valles Marineris (Mars)", yanlislar: ["Grand Canyon (Dünya)", "Caloris Havzası", "Olympus Mons"] },
    { s: "Merkür'ün yüzeyindeki en büyük çarpışma kraterlerinden birinin adı nedir?", c: "Caloris Havzası", yanlislar: ["Tombaugh Regio", "Valles Marineris", "Tharsis"] },
    { s: "Plüton'un kalbe benzetilen ünlü buz ovasının resmi adı nedir?", c: "Tombaugh Regio", yanlislar: ["Sagan Ovası", "Armstrong Bölgesi", "Galileo Çukuru"] },
    { s: "Güneş sisteminin dışına çıkan ilk insan yapımı araç hangisidir?", c: "Voyager 1", yanlislar: ["Apollo 11", "Hubble", "Sputnik"] },
    { s: "Voyager 1 ve 2 uzay araçları hangi yıl fırlatılmıştır?", c: "1977", yanlislar: ["1969", "1985", "1990"] },
    { s: "Ay'a insanlı ilk iniş hangi uzay göreviyle gerçekleştirilmiştir?", c: "Apollo 11", yanlislar: ["Sputnik 1", "Voyager", "Discovery"] },
    { s: "Apollo 11 modülünün Ay'a inen kısmının adı neydi?", c: "Kartal (Eagle)", yanlislar: ["Apollo", "Sputnik", "Columbia"] },
    { s: "Uzay mekiklerinden ilki olan ve uzaya giden araç hangisidir?", c: "Columbia", yanlislar: ["Challenger", "Discovery", "Atlantis"] },
    { s: "Astronotların uzay boşluğunda giydiği özel koruyucu kıyafetin adı nedir?", c: "Uzay giysisi (EMU)", yanlislar: ["Dalgıç kıyafeti", "İtfaiyeci elbisesi", "Pilot ceketi"] },
    { s: "Uzayda yerçekimsizlikten dolayı astronotların boyu ne kadar uzayabilir?", c: "Birkaç santimetre", yanlislar: ["Yarı yarıya uzar", "Hiç değişmez", "1 metre uzar"] },
    { s: "Güneş sistemindeki en hızlı dönen gezegen hangisidir?", c: "Jüpiter", yanlislar: ["Merkür", "Dünya", "Neptün"] },
    { s: "Venüs'ün kendi etrafındaki dönüş süresi mi yoksa Güneş etrafındaki dönüş süresi mi daha uzundur?", c: "Kendi etrafındaki dönüşü (günü yılından uzun)", yanlislar: ["Yılı gününden uzundur", "İkisi eşittir", "Kıyaslanamaz"] },
    { s: "Merkür'ün etrafında atmosfer olmamasının sebebi nedir?", c: "Kütleçekiminin zayıf olması", yanlislar: ["Güneş'e yakın olması", "Çok soğuk olması", "Su olmaması"] },
    { s: "Ay'ın yaşının yaklaşık ne kadar olduğu tahmin edilmektedir?", c: "4.5 milyar yıl", yanlislar: ["10 bin yıl", "100 milyon yıl", "10 milyar yıl"] },
    { s: "Yıldızların tayf türleri harflere ayrılır; en sıcak yıldızlar hangi harfle başlar?", c: "O sınıfı", yanlislar: ["M sınıfı", "G sınıfı", "Z sınıfı"] },
    { s: "Güneşimiz tayf sınıflandırmasına göre hangi gruptadır?", c: "G sınıfı", yanlislar: ["O sınıfı", "M sınıfı", "B sınıfı"] },
    { s: "Samanyolu galaksisinin merkezinde ne olduğu düşünülmektedir?", c: "Dev bir süper kütleli karadelik", yanlislar: ["Dev bir güneş", "Kocaman elmas", "Boşluk"] },
    { s: "Güneş sistemindeki en büyük asteroit kuşağı hangi iki gezegen arasında yer alır?", c: "Mars ile Jüpiter", yanlislar: ["Dünya ile Mars", "Satürn ile Uranüs", "Venüs ile Dünya"] },
    { s: "Güneş sisteminin en dışında bulunan ve buzlu gök cisimlerinin oluşturduğu bölgeye ne ad verilir?", c: "Kuiper Kuşağı", yanlislar: ["Asteroit Kuşağı", "Oort Bulutu", "Manyetik Kuşak"] },
    { s: "Evrendeki en yaygın element hangisidir?", c: "Hidrojen", yanlislar: ["Oksijen", "Demir", "Karbon"] },
    { s: "Yıldızların doğduğu gaz ve toz bulutlarına ne denir?", c: "Nebula", yanlislar: ["Pulsar", "Kuasar", "Meteor"] },
    { s: "Dünya'nın uydusu Ay'ın yüzeyindeki karanlık düzlüklere ne ad verilir?", c: "Maria (Deniz)", yanlislar: ["Krater", "Vadi", "Çöl"] },
    { s: "Uranüs'ün diğer gezegenlerden farklı olarak dönme ekseni neredeyse ne kadar eğiktir?", c: "98 derece (yan yatmıştır)", yanlislar: ["23 derece", "0 derece", "45 derece"] },
    { s: "Gök cisimlerini inceleyen bilim dalına ne denir?", c: "Astronomi", yanlislar: ["Biyoloji", "Jeoloji", "Fizik"] },
    { s: "Yeryüzüne düşen göktaşı parçalarına ne denir?", c: "Meteorit", yanlislar: ["Meteor", "Nebula", "Asteroit"] },
    { s: "Güneş sistemindeki buz devi gezegenler hangileridir?", c: "Uranüs ve Neptün", yanlislar: ["Jüpiter ve Satürn", "Merkür ve Venüs", "Dünya ve Mars"] },
    { s: "Güneş sistemindeki en büyük ikinci gezegen hangisidir?", c: "Satürn", yanlislar: ["Uranüs", "Neptün", "Dünya"] },
    { s: "Güneş sisteminde Güneş'e en yakın olan buz devi gezegen hangisidir?", c: "Uranüs", yanlislar: ["Neptün", "Satürn", "Jüpiter"] },
    { s: "Samanyolu galaksisinin biçimi nasıldır?", c: "Sarmal (Spiral)", yanlislar: ["Küresel", "Kare", "Düzensiz"] },
    { s: "Samanyolu galaksisine en yakın büyük komşu galaksi hangisidir?", c: "Andromeda", yanlislar: ["Sombrero", "Üçgen", "Büyük Macellan"] },
    { s: "Evrendeki en güçlü çekim kuvvetine sahip nesneler nedir?", c: "Karadelik", yanlislar: ["Nötron yıldızı", "Beyaz cüce", "Kuyruklu yıldız"] },
    { s: "Bir yıldızın karadeliğe dönüşmesi için ne kadar kütleye sahip olması gerekir?", c: "Çok büyük dev kütlelere", yanlislar: ["Küçük kütlelere", "Dünya kadar kütleye", "Ay kadar kütleye"] },
    { s: "Türkiye'nin ilk gözlem uydularından biri hangisidir?", c: "Göktürk veya Rasat", yanlislar: ["Sputnik", "Hubble", "Voyager"] },
    { s: "Uluslararası Uzay İstasyonu (ISS) hangi yılda hizmete girmiştir?", c: "1998", yanlislar: ["1969", "1981", "2010"] },
    { s: "Uzay araçlarının dünyaya dönerken yanmasını önleyen sisteme ne denir?", c: "Isı kalkanı", yanlislar: ["Soğutma kliması", "Su perdesi", "Rüzgar kesici"] },
    { s: "Mars'ın yüzeyinde su arayan ünlü NASA araçlarının genel adı nedir?", c: "Gezgin (Rover - Curiosity / Perseverance)", yanlislar: ["Uçak", "Sondaj", "Roket"] },
    { s: "Kuiper Kuşağı Güneş sisteminin neresinde yer alır?", c: "Neptün'ün ötesinde", yanlislar: ["Merkür'ün yanında", "Mars ile Jüpiter arasında", "Güneş'in merkezinde"] },
    { s: "Güneş sistemindeki en küçük uydu hangisidir?", c: "Deimos", yanlislar: ["Phobos", "Europa", "Titan"] },
    { s: "Jüpiter'in en büyük uydusu hangisidir?", c: "Ganymede", yanlislar: ["Callisto", "Io", "Europa"] },
    { s: "Satürn'ün halkaları çoğunlukla hangi maddeden oluşur?", c: "Su buzu ve kaya parçacıkları", yanlislar: ["Saf demir", "Katı gaz", "Kömür tozu"] },
    { s: "Uranüs'ün en büyük uydusunun adı nedir?", c: "Titania", yanlislar: ["Oberon", "Umbriel", "Ariel"] },
    { s: "Neptün'ün en büyük uydusu Triton'un yörünge hareketi nasıldır?", c: "Gezegenin dönüş yönünün tersine (retrograde)", yanlislar: ["Gezegenle aynı yönde", "Kutuplar üzerinde dik", "Mükemmel dairesel ve sabit"] },
    { s: "Güneş sistemindeki en yüksek dağ olan Olympus Mons kaç kilometre yüksekliktedir?", c: "Yaklaşık 22 kilometre", yanlislar: ["8 kilometre", "12 kilometre", "35 kilometre"] },
    { s: "Mars'taki en büyük kanyon olan Valles Marineris'in uzunluğu yaklaşık ne kadardır?", c: "4000 kilometre", yanlislar: ["400 kilometre", "100 kilometre", "10000 kilometre"] },
    { s: "Venüs'ün kendi etrafındaki bir dönüşü ne kadar sürer?", c: "243 Dünya günü", yanlislar: ["24 saat", "365 gün", "88 gün"] },
    { s: "Merkür'ün Güneş etrafındaki bir tam turu (yılı) kaç Dünya günü sürer?", c: "88 gün", yanlislar: ["365 gün", "30 gün", "225 gün"] },
    { s: "Güneş'in çekirdeğinde gerçekleşen nükleer füzyon süreci hangi elementi hangi elemente dönüştürür?", c: "Hidrojeni Helyuma", yanlislar: ["Helyumu Karbona", "Demiri Nikele", "Karbonu Oksijene"] },
    { s: "Güneş'in görünür en dış tabakasına ne ad verilir?", c: "Fotosfer", yanlislar: ["Korona", "Kromosfer", "Çekirdek"] },
    { s: "Güneş lekelerinin daha karanlık görünmesinin temel sebebi nedir?", c: "Diğer bölgelere göre daha soğuk olmaları", yanlislar: ["Üzerlerinde bulut olması", "Delik olmaları", "Gölge düşmesi"] },
    { s: "Güneş rüzgarlarının Dünya'nın atmosferine girmesini engelleyen temel kalkan nedir?", c: "Manyetosfer (Manyetik alan)", yanlislar: ["Ozon tabakası", "Okyanuslar", "Bulutlar"] },
    { s: "Atmosferin ozon tabakası hangi katmanda yer alır?", c: "Stratosfer", yanlislar: ["Troposfer", "Mezosfer", "Termosfer"] },
    { s: "Hava olaylarının (yağmur, rüzgar vb.) gerçekleştiği atmosfer katmanı hangisidir?", c: "Troposfer", yanlislar: ["Stratosfer", "İyonosfer", "Ekzosfer"] },
    { s: "Kutup ışıkları (Aurora) atmosferin hangi katmanında gözlemlenir?", c: "Termosfer / İyonosfer", yanlislar: ["Troposfer", "Stratosfer", "Mezosfer"] },
    { s: "Bir yıldızın parlaklığını dünyadan görünen uzaklığına göre değil, standart bir mesafeden ölçen parlaklık birimi nedir?", c: "Mutlak Kadir", yanlislar: ["Görünen Kadir", "Işık yılı", "Paralaks"] },
    { s: "Yıldızların mesafesini ölçmek için kullanılan açısal kayma yönteminin adı nedir?", c: "Paralaks yöntemi", yanlislar: ["Tayf analizi", "Doppler etkisi", "Spektroskopi"] },
    { s: "Güneş sisteminin Samanyolu galaksisi etrafındaki bir tam turu ne kadar sürede tamamlanır?", c: "Yaklaşık 225-250 milyon yıl", yanlislar: ["1 milyon yıl", "10 bin yıl", "5 milyar yıl"] },
    { s: "Samanyolu galaksisinin merkezi hangi takımyıldız yönündedir?", c: "Yay (Sagittarius)", yanlislar: ["Orion", "Büyük Ayı", "Kutup Yıldızı"] },
    { s: "Evrenin en büyük yapılarından biri olan galaksi kümelerini bir arada tutan görünmez madde türüne ne denir?", c: "Karanlık Madde", yanlislar: ["Karanlık Enerji", "Antimadde", "Baryonik Madde"] },
    { s: "Evrenin hızlanarak genişlemesine sebep olan gizemli gücün adı nedir?", c: "Karanlık Enerji", yanlislar: ["Karanlık Madde", "Kütleçekim", "Elektromanyetik Kuvvet"] },
    { s: "Albert Einstein'ın genel görelilik teorisinde uzay-zaman dokusunda kütle tarafından oluşturulan bükülmeye ne denir?", c: "Kütleçekim (Gravitasyonel bükülme)", yanlislar: ["Manyetik alan", "Işık kırılması", "Merkezkaç etkisi"] },
    { s: "İlk defa doğrudan gözlemlenen kütleçekim dalgaları hangi olay sonucunda tespit edilmiştir?", c: "İki karadeliğin birleşmesi", yanlislar: ["Süpernova patlaması", "Güneş fırtınası", "Kuyruklu yıldız çarpışması"] },
    { s: "Yıldızların evrim sürecinde demir elementinin üretilmesi neyin habercisidir?", c: "Yıldızın çekirdek çöküşü yaşayacağının (Süpernova)", yanlislar: ["Yıldızın büyüyeceğinin", "Yıldızın soğuyup gezegen olacağının", "Yıldızın renginin maviye döneceğinin"] },
    { s: "Süpernova patlaması sonrasında çok büyük kütleli yıldızlardan geriye kalan aşırı yoğun cisim nedir?", c: "Nötron yıldızı veya Karadelik", yanlislar: ["Beyaz cüce", "Kahverengi cüce", "Nebula"] },
    { s: "Çok hızlı dönen ve kutuplarından düzenli radyo dalgaları yayan nötron yıldızlarına ne ad verilir?", c: "Pulsar", yanlislar: ["Kuasar", "Magnetar", "Süpernova"] },
    { s: "Evrendeki en güçlü manyetik alana sahip nötron yıldızı türü hangisidir?", c: "Magnetar", yanlislar: ["Pulsar", "Kuasar", "Beyaz Cüce"] },
    { s: "Çok uzak galaksilerin merkezinde yer alan ve devasa kara delikler tarafından beslenen aşırı parlak cisimlere ne denir?", c: "Kuasar", yanlislar: ["Pulsar", "Nebula", "Meteor"] },
    { s: "Güneş'in ömrünün sonunda dönüşeceği kararlı küçük ve yoğun yıldız kalıntısı nedir?", c: "Beyaz Cüce", yanlislar: ["Nötron Yıldızı", "Karadelik", "Kırmızı Dev"] },
    { s: "Yeterli kütleye ulaşamadığı için nükleer füzyonu başlatamamış 'başarısız yıldızlara' ne ad verilir?", c: "Kahverengi Cüce", yanlislar: ["Beyaz Cüce", "Sarı Cüce", "Kırmızı Cüce"] },
    { s: "Güneş sistemindeki en yaygın elementlerden sonra ikinci sırada en çok bulunan element hangisidir?", c: "Helyum", yanlislar: ["Oksijen", "Karbon", "Demir"] },
    { s: "Güneş sisteminin dış sınırını oluşturan ve Voyager 1'in geçtiği, güneş rüzgarlarının durduğu bölgeye ne denir?", c: "Heliopoz", yanlislar: ["Oort Bulutu", "Kuiper Kuşağı", "Van Allen Kuşağı"] },
    { s: "Dünya'nın etrafını saran ve radyasyon tutan iki halka şeklindeki bölgeye ne denir?", c: "Van Allen Radyasyon Kuşakları", yanlislar: ["Kuiper Kuşağı", "Asteroit Kuşağı", "Oort Bulutu"] },
    { s: "Uluslararası Uzay İstasyonu (ISS) yerden yaklaşık kaç kilometre yükseklikte yörüngededir?", c: "400 kilometre", yanlislar: ["40 kilometre", "4000 kilometre", "35000 kilometre"] },
    { s: "Haberleşme uydularının bulunduğu, Dünya'nın dönme hızıyla aynı hızda döndüğü yörünge türüne ne denir?", c: "Jeosenkron / Jeostasyoner yörünge", yanlislar: ["Alçak Dünya yörüngesi", "Kutupsal yörünge", "Eliptik yörünge"] },
    { s: "Uzay araçlarının manevra yaparken yakıt tasarrufu sağlamak için kullandığı, elektrik yüklü gazları hızlandıran sistem nedir?", c: "İyon İtki Sistemi", yanlislar: ["Kimyasal Roket Motoru", "Nükleer Reaktör", "Katı Yakıtlı Booster"] },
    { s: "Güneş ışığının basıncını kullanarak uzayda hareket etmeyi sağlayan teknolojiye ne denir?", c: "Solar Yelken (Güneş yelkeni)", yanlislar: ["İyon motoru", "Nükleer roket", "Plazma motoru"] },
    { s: "Günümüz uzay araçlarında yüksek verim sağlamak için yakıt olarak iyonize gaz kullanan motor türü nedir?", c: "İyon motoru", yanlislar: ["Kimyasal roket", "Buhar motoru", "Dizel motor"] },
    { s: "Ay'ın yüzeyinde bulunan ince toz ve kırık kaya tabakasına verilen bilimsel ad nedir?", c: "Regolit", yanlislar: ["Lav tabakası", "Kil", "Toprak"] },
    { s: "Ay'ın Dünya'ya en yakın olduğu konuma ne ad verilir?", c: "Yerberi (Perigee)", yanlislar: ["Yeröte (Apogee)", "Günberi", "Günöte"] },
    { s: "Ay'ın Dünya'ya en uzak olduğu konuma ne ad verilir?", c: "Yeröte (Apogee)", yanlislar: ["Yerberi", "Günberi", "Günöte"] },
    { s: "Dünya'nın Güneş'e en yakın olduğu döneme ne denir?", c: "Günberi (Perihel)", yanlislar: ["Günöte (Aphel)", "Yerberi", "Yeröte"] },
    { s: "Dünya'nın Güneş'e en uzak olduğu döneme ne denir?", c: "Günöte (Aphel)", yanlislar: ["Günberi", "Yerberi", "Yeröte"] },
    { s: "Yıl boyunca gece ve gündüz sürelerinin birbirine eşit olduğu iki güne ne ad verilir?", c: "Ekinoks (Equinox)", yanlislar: ["Gündönümü (Solstice)", "Perihel", "Aphel"] },
    { s: "Kuzey yarımkürede yılın en uzun gecesinin yaşandığı tarihe ne denir?", c: "Kış Gündönümü (21 Aralık)", yanlislar: ["Yaz Gündönümü", "Bahar Ekinoksu", "Sonbahar Ekinoksu"] },
    { s: "Kuzey yarımkürede yılın en uzun gündüzünün yaşandığı tarihe ne denir?", c: "Yaz Gündönümü (21 Haziran)", yanlislar: ["Kış Gündönümü", "Bahar Ekinoksu", "Sonbahar Ekinoksu"] },
    { s: "Gökbilimde iki gök cismi arasındaki mesafeyi ölçmek için kullanılan ve Güneş-Dünya arasındaki ortalama mesafeye eşit olan birim nedir?", c: "Astronomik Birim (AU)", yanlislar: ["Işık yılı", "Parsek", "Kilometre"] },
    { s: "Işık yılının yaklaşık 3.26 katına eşit olan büyük uzay mesafe ölçü birimi nedir?", c: "Parsek (pc)", yanlislar: ["Astronomik Birim", "Kilometre", "Megametre"] },
    { s: "Güneş sistemindeki en büyük kraterlerden biri olan Caloris Havzası hangi gezegendedir?", c: "Merkür", yanlislar: ["Mars", "Venüs", "Ay"] },
    { s: "Mars'ın iki uydusu Phobos ve Deimos'un kökeni hakkında en yaygın bilimsel teori nedir?", c: "Asteroit kuşağından kapılagelmiş göktaşları olmaları", yanlislar: ["Mars'ın parçalanmış halkaları olmaları", "Güneş'le birlikte oluşmaları", "Dünya'dan fırlayan parçalar olmaları"] },
    { s: "Jüpiter'in uydusu Europa'nın buzlu yüzeyinin altında sıvı okyanus olmasının temel sebebi nedir?", c: "Gel-git (tidal) ısınması", yanlislar: ["Güneş ışınları", "Radyoaktif çekirdek", "Volkanik patlamalar"] },
    { s: "Satürn'ün uydusu Titan'ın atmosferinde sıvı halde bulunan hidrokarbonlar ağırlıklı olarak hangisidir?", c: "Metan ve Etan", yanlislar: ["Su ve Oksijen", "Karbondioksit ve Azot", "Amonyak ve Helyum"] },
    { s: "Jüpiter'in uydusu Io'nun aşırı derecede volkanik olmasının sebebi nedir?", c: "Jüpiter ve diğer uyduların yarattığı güçlü gel-git çekim sürtünmesi", yanlislar: ["Çok sıcak bir çekirdeğe sahip olması", "Güneş'e çok yakın olması", "Yüzeyinde metan yanması"] },
    { s: "Satürn'ün uydusu Enceladus'un güney kutbundaki çatlaklardan uzaya fışkıran maddeler neyi kanıtlar?", c: "Yeraltında sıvı su okyanusu ve hidrotermal etkinlik olduğunu", yanlislar: ["Yüzeyin tamamen altınla kaplı olduğunu", "Atmosferin zehirli olduğunu", "Gezegenin iç kısmının boş olduğunu"] },
    { s: "Uranüs ve Neptün'ün manto tabakasında yüksek basınç altında hangi sıvının okyanuslar oluşturduğu düşünülür?", c: "Su, amonyak ve metan karışımı (sıvı buz)", yanlislar: ["Sıvı demir", "Sıvı hidrojen", "Sıvı karbondioksit"] },
    { s: "Güneş sisteminde kendi ekseni etrafında en dik konumda dönen (eksen eğikliği en az olan) gezegen hangisidir?", c: "Merkür", yanlislar: ["Dünya", "Jüpiter", "Venüs"] },
    { s: "Güneş sisteminde halkası olan gezegenler sırasıyla hangi dörtlüdür?", c: "Jüpiter, Satürn, Uranüs, Neptün", yanlislar: ["Merkür, Venüs, Dünya, Mars", "Mars, Jüpiter, Satürn, Plüton", "Uranüs, Neptün, Plüton, Eris"] },
    { s: "Güneş sistemindeki en büyük asteroit ve ilk cüce gezegen olarak sınıflandırılan gök cismi hangisidir?", c: "Ceres", yanlislar: ["Vesta", "Pallas", "Eris"] },
    { s: "Plüton'un da dahil olduğu Neptün ötesi cisimlerin bulunduğu bölgenin genel adı nedir?", c: "Kuiper Kuşağı", yanlislar: ["Asteroit Kuşağı", "Oort Bulutu", "Van Allen Kuşağı"] },
    { s: "Uzun periyotlu kuyruklu yıldızların kaynağı olan ve Güneş sistemini küre şeklinde çevreleyen en dış bölge nedir?", c: "Oort Bulutu", yanlislar: ["Kuiper Kuşağı", "Asteroit Kuşağı", "Helyosfer"] },
    { s: "Halley Kuyruklu Yıldızı gibi kısa periyotlu kuyruklu yıldızlar genellikle nereden gelir?", c: "Kuiper Kuşağı", yanlislar: ["Oort Bulutu", "Asteroit Kuşağı", "Galaksi Merkezi"] },
    { s: "Bir kuyruklu yıldızın güneşe yaklaşırken oluşan iki ana kuyruğu hangi maddelerden oluşur?", c: "İyon (gaz) kuyruğu ve toz kuyruğu", yanlislar: ["Su kuyruğu ve demir kuyruğu", "Buz kuyruğu ve ateş kuyruğu", "Manyetik kuyruk ve ışık kuyruğu"] },
    { s: "Atmosfere yüksek hızla giren bir göktaşının (meteoroitin) ışık saçarak parlaması olayına ne ad verilir?", c: "Meteor (Kayan yıldız)", yanlislar: ["Meteorit", "Kuyruklu yıldız", "Asteroid"] },
    { s: "Yeryüzüne ulaşmayı başaran göktaşı kalıntılarına ne ad verilir?", c: "Meteorit", yanlislar: ["Meteor", "Nebula", "Pulsar"] },
    { s: "Dünya'ya çarparak büyük kraterler oluşturan gök cisimlerinin uzaydaki genel adına ne denir?", c: "Asteroit / Near-Earth Object (NEO)", yanlislar: ["Kuyruklu yıldız", "Yapay uydu", "Gezegencik"] },
    { s: "Güneş sistemindeki gezegenlerin güneşe olan uzaklıklarını basit bir matematiksel oranla veren kuralın adı nedir?", c: "Titius-Bode Yasası", yanlislar: ["Kepler Yasası", "Hubble Yasası", "Newton Kanunu"] },
    { s: "Gezegenlerin güneş etrafındaki yörüngelerinin elips olduğunu ve odaklardan birinde güneşin yer aldığını söyleyen yasa kimindir?", c: "Kepler'in Birinci Yasası", yanlislar: ["Newton", "Galileo", "Einstein"] },
    { s: "Gezegenlerin güneşe yaklaştıkça daha hızlı, uzaklaştıkça daha yavaş hareket ettiğini belirten yasa nedir?", c: "Kepler'in İkinci Yasası (Alanlar Kanunu)", yanlislar: ["Kepler'in Birinci Yasası", "Newton'un Hareket Kanunu", "Hubble Yasası"] },
    { s: "Gezegenlerin yörünge periyotlarının karesinin, güneşe olan ortalama uzaklıklarının küpüne oranının sabit olduğunu belirten yasa nedir?", c: "Kepler'in Üçüncü Yasası", yanlislar: ["Kepler'in İkinci Yasası", "Einstein Görelilik Teorisi", "Bode Yasası"] },
    { s: "Ay'ın Dünya üzerindeki okyanuslarda gel-git (med-cezir) olayına sebep olmasının temel fiziksel nedeni nedir?", c: "Ay'ın uyguladığı kütleçekim kuvvetinin Dünya'nın farklı noktalarında farklı şiddette olması", yanlislar: ["Ay'ın kendi etrafında dönmesi", "Dünya'nın atmosfer basıncı", "Güneş'in rüzgarları"] },
    { s: "Güneş ve Ay'ın Dünya ile aynı hizaya geldiği (dünya-güneş-ay veya güneş-ay-dünya) dönemlerde yaşanan en yüksek gel-git olayına ne denir?", c: "Spring Tide (Canlı / Büyük gel-git)", yanlislar: ["Neap Tide (Ölü gel-git)", "Ekinoks", "Solstice"] },
    { s: "Ay'ın ve Güneş'in birbirine dik açı oluşturduğu dönemlerde yaşanan en zayıf gel-git olayına ne denir?", c: "Neap Tide (Ölü gel-git)", yanlislar: ["Spring Tide", "Perigee", "Apogee"] },
    { s: "Uzay boşluğunda yön bulmak ve konum belirlemek için pulsarların yanıp sönme frekanslarını kullanan navigasyon sistemine ne denir?", c: "Pulsar Tabanlı Navigasyon (XNAV)", yanlislar: ["GPS", "GLONASS", "Galileo"] },
    { s: "Uzay araçlarının manevra yaparken yakıt tasarrufu sağlamak için kullandığı, elektrik yüklü gazları hızlandıran sistem nedir?", c: "İyon İtki Sistemi", yanlislar: ["Kimyasal Roket Motoru", "Nükleer Reaktör", "Katı Yakıtlı Booster"] },
    { s: "Güneş sistemindeki en büyük manyetik alana sahip gezegen hangisidir?", c: "Jüpiter", yanlislar: ["Satürn", "Dünya", "Neptün"] },
    { s: "Uranüs ve Neptün'ün manyetik alanlarının en büyük garip özelliği nedir?", c: "Gezegenin dönme eksenine göre çok fazla eğik ve merkezden kaçık olmaları", yanlislar: ["Çok zayıf olmaları", "Sürekli yön değiştirmeleri", "Hiç bulunmamaları"] },
    { s: "Venüs gezegeninin kendi etrafındaki dönüş yönü nasıldır?", c: "Doğudan batıya (saat yönünün tersi)", yanlislar: ["Batıdan doğuya", "Kuzeyden güneye", "Dikey eksende"] },
    { s: "Güneş sisteminde Güneş'e en yakın karasal gezegen hangisidir?", c: "Merkür", yanlislar: ["Venüs", "Dünya", "Mars"] },
    { s: "Güneş sisteminde Güneş'e en uzak gaz devi gezegen hangisidir?", c: "Neptün", yanlislar: ["Uranüs", "Satürn", "Jüpiter"] },
    { s: "Yıldızların renkleri ile sıcaklıkları arasındaki ilişkiye göre, turuncu/kırmızı yıldızlar hangi sıcaklık aralığındadır?", c: "Düşük sıcaklık (3000 - 4000 derece)", yanlislar: ["Çok yüksek sıcaklık (30000 derece)", "Orta sıcaklık (6000 derece)", "Sıfır derece"] },
    { s: "Mavi renkli dev yıldızların yüzey sıcaklığı yaklaşık kaç dereceyi bulabilir?", c: "10.000 - 30.000+ derece", yanlislar: ["3.000 derece", "5.500 derece", "1.000 derece"] },
    { s: "Samanyolu galaksisinin türü spiraldir; peki merkezindeki çekirdeğin yapısı nasıldır?", c: "Çubuklu spiral (Barred spiral)", yanlislar: ["Düzensiz küme", "Eliptik halka", "Saf küresel"] },
    { s: "Andromeda galaksisi ile Samanyolu galaksisinin milyarlarca yıl sonra çarpışıp birleşmesiyle oluşacağı tahmin edilen yeni dev galaksiye ne ad verilmektedir?", c: "Milkomeda (Milkdromeda)", yanlislar: ["Andromenyolu", "SuperSamanyolu", "MegaGalaksi"] },
    { s: "Evrenin yaşının yaklaşık 13.8 milyar yıl olduğunu ve hızla genişlediğini hassas bir şekilde ölçen uzay teleskobunun adı nedir?", c: "Planck Uzay Teleskobu", yanlislar: ["Hubble", "Kepler", "Spitzer"] },
    { s: "Güneş sisteminin ötesinde ilk defa bir ana kol yıldızı etrafında dönen ötegezegen hangi yıldız sisteminde keşfedilmiştir?", c: "51 Pegasi b", yanlislar: ["Proxima Centauri b", "Trappist-1", "Sirius b"] },
    { s: "Gezegenlerin geçiş (transit) yöntemini kullanarak yıldızının önünden geçerken ışık miktarındaki düşüşü gözlemleyen ve binlerce ötegezegen keşfeden uzay teleskobu hangisidir?", c: "Kepler Uzay Teleskobu", yanlislar: ["James Webb", "Chandra", "Compton"] },
    { s: "Gezegen avcılığında kullanılan 'radyal hız' yöntemi neyi ölçer?", c: "Yıldızın gezegenin çekimiyle yaptığı minik sallantı ve hız değişimlerini", yanlislar: ["Gezegenin yaydığı radyasyonu", "Yıldızın yaydığı ses dalgalarını", "Gezegenin rengini"] },
    { s: "Yaşanabilir kuşak (Goldilocks zone) bir yıldız etrafında neyin bulunabileceği mesafeyi ifade eder?", c: "Sıvı suyun", yanlislar: ["Saf altının", "Katı demirin", "Metan gazının"] },
    { s: "Mars'ın yüzeyinde geçmişte su olduğunu kanıtlayan, suyun aşındırmasıyla oluşan mineral birikintilerinin adı nedir?", c: "Kil (Silyat / Kil mineralleri)", yanlislar: ["Demir tozu", "Kömür tabakası", "Volkanik kül"] },
    { s: "Uluslararası Uzay İstasyonu'nda (ISS) astronotların kemik ve kas kaybını engellemek için günde kaç saat egzersiz yapması zorunludur?", c: "2 saat", yanlislar: ["30 dakika", "5 dakika", "Hiç gerek yoktur"] },
    { s: "Uzay boşluğunda astronotların yaşadığı sıvı dengesi değişiminden dolayı vücut sıvılarının yukarı çıkması sonucu oluşan duruma ne denir?", c: "Puffy face (Şiş yüz sendromu)", yanlislar: ["Yerçekimi hastalığı", "Uzay körlüğü", "Kalsiyum kaybı"] },
    { s: "Uzayda astronotların sesleri Dünya'dakinden farklı duyulmasının temel nedeni nedir?", c: "Kabin içindeki hava basıncı ve gaz bileşiminin farklı olması", yanlislar: ["Yerçekimi olmaması", "Kulak zarının esnemesi", "Telsiz mikrofonları"] },
    { s: "Güneş'in dünyaya olan ortalama uzaklığı kaç kilometredir?", c: "Yaklaşık 150 milyon kilometre", yanlislar: ["15 milyon kilometre", "1 milyar kilometre", "50 milyon kilometre"] },
    { s: "Ay'ın Dünya'ya her yıl hangi miktarda uzaklaştığı hesaplanmaktadır?", c: "Yaklaşık 3.8 santimetre", yanlislar: ["10 santimetre", "1 metre", "Hiç uzaklaşmıyor"] },
    { s: "Güneş sistemindeki en büyük asteroit olan Vesta hangi bölgede yer alır?", c: "Asteroit Kuşağı", yanlislar: ["Kuiper Kuşağı", "Oort Bulutu", "Mars'ın yörüngesi"] },
    { s: "Güneş sistemindeki en uzak cüce gezegenlerden biri olan ve adını mitolojik bir tanrıçadan alan cisim hangisidir?", c: "Eris", yanlislar: ["Ceres", "Haumea", "Makemake"] },
    { s: "Satürn'ün en dışındaki devasa halka sistemine ne ad verilir?", c: "E Halkası veya Phoebe Halkası", yanlislar: ["A Halkası", "B Halkası", "C Halkası"] },
    { s: "Uranüs'ün keşfi hangi yıl ve hangi astronom tarafından gerçekleştirilmiştir?", c: "1781 yılında William Herschel", yanlislar: ["1610 yılında Galileo", "1930 yılında Clyde Tombaugh", "1846 yılında Urbain Le Verrier"] },
    { s: "Neptün'ün varlığı fiziksel hesaplamalarla keşfedildikten sonra hangi yıl gözlemlenmiştir?", c: "1846 yılında", yanlislar: ["1781 yılında", "1900 yılında", "1930 yılında"] },
    { s: "Güneş sisteminde uydusu olmayan tek iki gezegenin ortak özelliği nedir?", c: "Güneş'e en yakın iki iç gezegen olmaları", yanlislar: ["Gaz devi olmaları", "Çok soğuk olmaları", "Halkalarının bulunması"] },
    { s: "Mars'ın ince atmosferinin büyük kısmını kaybetmesinin temel sebebi nedir?", c: "Küresel manyetik alanını zamanla yitirmesi ve güneş rüzgarları", yanlislar: ["Büyük bir asteroit çarpması", "Güneş'e çok yaklaşması", "Volkanik patlamalar"] },
    { s: "Venüs'ün yüzey sıcaklığının Merkür'den bile yüksek olmasının temel sebebi nedir?", c: "Aşırı güçlü sera etkisi", yanlislar: ["Güneş'e daha yakın olması", "Aktif lav nehirleri", "Uydusunun olmaması"] },
    { s: "Güneş'in atmosferinin en dış tabakası olan ve güneş tutulmalarında taç şeklinde görülen katman nedir?", c: "Korona", yanlislar: ["Fotosfer", "Kromosfer", "Çekirdek"] },
    { s: "Güneş'in kromosfer tabakasının hemen altında yer alan ve ışığın yayıldığı ana katman nedir?", c: "Fotosfer", yanlislar: ["Korona", "Radyasyon bölgesi", "Konveksiyon bölgesi"] },
    { s: "Yıldızlararası uzayda bulunan ve yeni yıldızların doğduğu soğuk gaz bulutlarına ne denir?", c: "Moleküler Bulut (Dev moleküler bulut)", yanlislar: ["Gezegenimsi nebula", "Karasal bulut", "Pulsar bulutu"] },
    { s: "Ömrünün sonuna gelen orta büyüklükteki bir yıldızın dış katmanlarını uzaya yayarak oluşturduğu parlak gaz halkasına ne denir?", c: "Gezegenimsi Nebula (Planetary Nebula)", yanlislar: ["Süpernova kalıntısı", "Karasal disk", "Kuyruklu yıldız kuyruğu"] },
    { s: "Kraterlerin içindeki gölgeli bölgelerde su buzunun keşfedildiği ilk ve en büyük gök cismi hangisidir?", c: "Ay", yanlislar: ["Mars", "Merkür", "Venüs"] },
    { s: "Uluslararası Uzay İstasyonu'nda (ISS) elektrik ihtiyacını karşılamak için ne kullanılır?", c: "Dev Güneş panelleri", yanlislar: ["Nükleer santral", "Rüzgar türbinleri", "Hidroelektrik jeneratör"] },
    { s: "Uzay roketlerinin fırlatılış sırasında yerçekimini yenmek için ulaştığı hız sınırına ne ad verilir?", c: "Kurtulma hızı (Escape velocity)", yanlislar: ["Işık hızı", "Ses hızı", "Yörünge hızı"] },
    { s: "Dünya'nın yüzeyinden uzaya çıkmak için gereken saniyede kaç kilometre civarındaki kurtulma hızı gerekir?", c: "Saniyede yaklaşık 11.2 kilometre", yanlislar: ["Saniyede 3 kilometre", "Saniyede 30 kilometre", "Saniyede 1 kilometre"] },
    { s: "Güneş sistemindeki en büyük kanyon olan Valles Marineris hangi gezegendedir?", c: "Mars", yanlislar: ["Venüs", "Dünya", "Merkür"] },
    { s: "Güneş sistemindeki en büyük ikinci uydu olan Titan hangi gezegene aittir?", c: "Satürn", yanlislar: ["Jüpiter", "Uranüs", "Neptün"] },
    { s: "Jüpiter'in buzlu uydusu Europa'nın yüzeyindeki çizgisel ve kırık yapıların oluşma sebebi nedir?", c: "Altındaki sıvı okyanusun gel-git hareketleriyle buz kabuğunu zorlaması", yanlislar: ["Meteor çarpmaları", "Volkanik lav akıntıları", "Güneş rüzgarları"] },
    { s: "Uranüs'ün neredeyse tamamen yan yatmış şekilde dönmesinin arkasındaki en güçlü teori nedir?", c: "Geçmişte büyük protogezegenlerle şiddetli çarpışmalar yaşaması", yanlislar: ["Güneş'in kütleçekim baskısı", "Halkalarının ağır olması", "Çok hızlı dönmesi"] },
    { s: "Neptün'ün en belirgin yüzey özelliklerinden biri olan ve fırtına olduğu bilinen koyu lekenin adı nedir?", c: "Büyük Karanlık Leke", yanlislar: ["Büyük Kırmızı Leke", "Mavi Girdap", "Kuzey Çukuru"] },
    { s: "Plüton'un kalbe benzetilen devasa buz ovasının bilimsel adı nedir?", c: "Tombaugh Regio", yanlislar: ["Sagan Planitia", "Armstrong Regio", "Galileo Regio"] },
    { s: "Gökbilimde gök cisimlerinin parlaklığını ölçmek için kullanılan kadir ölçeğinde, sayı küçüldükçe parlaklık nasıl değişir?", c: "Parlaklık artar (daha parlak olur)", yanlislar: ["Parlaklık azalır", "Değişmez", "Renk değiştirir"] },
    { s: "Çıplak gözle görülebilen en sönük yıldızlar kadir ölçeğinde hangi değer civarındadır?", c: "6. kadir", yanlislar: ["1. kadir", "10. kadir", "0. kadir"] },
    { s: "Güneş'in görünür kadir (görünen parlaklık) değeri yaklaşık olarak kaçtır?", c: "Eksi 26.7 kadir", yanlislar: ["0 kadir", "Artı 5 kadir", "Eksi 2 kadir"] },
    { s: "Dolunay halindeki Ay'ın ortalama görünen kadir değeri yaklaşık kaçtır?", c: "Eksi 12.6 kadir", yanlislar: ["0 kadir", "Artı 5 kadir", "Eksi 25 kadir"] },
    { s: "Güneş sistemindeki gezegenler içinde en yoğun gezegen hangisidir?", c: "Dünya", yanlislar: ["Jüpiter", "Satürn", "Merkür"] },
    { s: "Güneş sistemindeki gezegenler içinde öz kütlesi sudan küçük olan tek gezegen hangisidir?", c: "Satürn", yanlislar: ["Jüpiter", "Uranüs", "Neptün"] },
    { s: "Yıldızların evrim sürecinde yakıt olarak kullandıkları hidrojenin tükenmesiyle birlikte genişleyip soğuyarak dönüştükleri aşamaya ne denir?", c: "Kırmızı Dev", yanlislar: ["Beyaz Cüce", "Süpernova", "Nötron Yıldızı"] },
    { s: "Güneş'in gelecekte Kırmızı Dev aşamasına geçtikten sonra yutması beklenen iç gezegenler hangileridir?", c: "Merkür, Venüs ve muhtemelen Dünya", yanlislar: ["Sadece Mars", "Jüpiter ve Satürn", "Hiçbirini yutmaz"] },
    { s: "Evrenin en soğuk yerlerinden biri olarak bilinen ve uzaydaki gaz bulutu olan Boomerang Nebulası'nın sıcaklığı yaklaşık kaç Kelvin'dir?", c: "1 Kelvin (eksi 272 derece)", yanlislar: ["100 Kelvin", "273 Kelvin", "0 Kelvin"] },
    { s: "Galaksilerin dönüş hızlarının merkezden uzaklaştıklarında düşmesi beklenirken sabit kalması hangi gizemli maddenin varlığını kanıtlar?", c: "Karanlık Madde", yanlislar: ["Karanlık Enerji", "Antimadde", "Normal Gaz"] },
    { s: "Evrenin ilk dönemlerinden kalan ve her yönden gelen en eski elektromanyetik ışıma kalıntısına ne ad verilir?", c: "Kozmik Mikrodalga Arka Plan Işıması (CMB)", yanlislar: ["Güneş Rüzgarı", "X-ışını Fırtınası", "Radyo Dalgası Kalıntısı"] },
    { s: "Büyük Patlama'dan hemen sonra evrenin çok küçük bir süre içinde ışıktan hızlı bir şekilde devasa boyutlara ulaşması olayına ne denir?", c: "Kozmik Enflasyon (Şişirme)", yanlislar: ["Karasal Çöküş", "Galaktik Genişleme", "Nükleer Füzyon"] },
    { s: "Güneş sistemindeki en büyük dağ olan Olympus Mons'un taban genişliği yaklaşık olarak ne kadardır?", c: "600 kilometre (İtalya büyüklüğünde)", yanlislar: ["50 kilometre", "10 kilometre", "2000 kilometre"] },
    { s: "Mars yüzeyinde rüzgar erozyonuyla oluşan ve insan yüzüne benzetilen ünlü bölgenin adı nedir?", c: "Cydonia Mensae", yanlislar: ["Tharsis", "Valles Marineris", "Hellas Planitia"] },
    { s: "Satürn'ün en büyük ikinci uydusu olan ve yüzeyindeki buz volkanlarıyla bilinen gök cismi hangisidir?", c: "Enceladus", yanlislar: ["Mimas", "Dione", "Rhea"] },
    { s: "Satürn'ün 'Ölüm Yıldızı' krateriyle ünlü, küçük ve ilginç uydusunun adı nedir?", c: "Mimas", yanlislar: ["Enceladus", "Tethys", "Iapetus"] },
    { s: "Satürn'ün iki renkli (bir yüzü kömür gibi siyah, diğer yüzü akçaağaç şurubu renginde) uydusunun adı nedir?", c: "Iapetus", yanlislar: ["Titan", "Hyperion", "Phoebe"] },
    { s: "Uranüs'ün süngerimsi ve düzensiz görünen uydusunun adı nedir?", c: "Hyperion (Satürn uydusudur; Uranüs için Miranda'dır)", yanlislar: ["Miranda", "Ariel", "Umbriel"] },
    { s: "Uranüs'ün yüzeyinde devasa uçurumlar ve karmaşık coğrafi şekiller barındıran uydusu hangisidir?", c: "Miranda", yanlislar: ["Oberon", "Titania", "Ariel"] },
    { s: "Neptün'ün yörüngesinde ters yönde dönen uydusu Triton'un zamanla Neptün tarafından yutulup neye dönüşeceği tahmin edilmektedir?", c: "Parçalanarak muazzam bir halka sistemine", yanlislar: ["Gezegenin merkezine çarpıp yok olacağına", "Güneş sisteminden fırlayacağına", "Karadeliğe döneceğine"] },
    { s: "Güneş sisteminde uydusu olan cüce gezegenler arasında en bilineni ve aynı zamanda uydusunun adı Charon olan cüce gezegen hangisidir?", c: "Plüton", yanlislar: ["Ceres", "Eris", "Haumea"] },
    { s: "Plüton'un uydusu Charon ile Plüton arasındaki kütleçekim kilidi (tidal locking) nasıldır?", c: "Karşılıklı olarak birbirlerine hep aynı yüzlerini bakarlar", yanlislar: ["Sadece Charon yüzünü saklar", "İkisi de hızla döner", "Kilitlenme yoktur"] },
    { s: "Haumea cüce gezegeninin en büyük fiziksel özelliği nedir?", c: "Hızlı dönüşü nedeniyle Amerikan futbolu topu gibi oval (uzatılmış) olması", yanlislar: ["Çok parlak halkalarının olması", "Yüzeyinde su okyanusu bulunması", "Kırmızı renkte olması"] },
    { s: "Haumea'nın etrafında dönen iki küçük uydunun adları nelerdir?", c: "Hi'iaka ve Namaka", yanlislar: ["Phobos ve Deimos", "Europa ve Io", "Nix ve Hydra"] },
    { s: "Plüton'un küçük dış uydularından olan Nix ve Hydra dışında keşfedilen diğer iki uydusunun adları nedir?", c: "Kerberos ve Styx", yanlislar: ["Titan ve Triton", "Atlas ve Prometheus", "Calisto ve Ganymede"] },
    { s: "Güneş sistemindeki en büyük asteroitlerden biri olan ve NASA'nın uzay aracı gönderdiği Vesta ne şeklindedir?", c: "Büyük ölçüde yuvarsuzdur ancak dev bir güney kutup kraterine sahiptir", yanlislar: ["Mükemmel bir küredir", "Patates şeklindedir", "Halkalıdır"] },
    { s: "Mars ile Jüpiter arasındaki asteroit kuşağında yer alan ve küresel formda olduğu için cüce gezegen sayılan tek cisim hangisidir?", c: "Ceres", yanlislar: ["Vesta", "Pallas", "Hygiea"] },
    { s: "Güneş sistemindeki asteroitlerin toplam kütlesi Dünya'nın kütlesiyle kıyaslandığında nasıldır?", c: "Dünya'nın uydusu Ay'ın kütlesinden bile çok daha küçüktür", yanlislar: ["Dünya'nın kütlesine eşittir", "Dünya'dan büyüktür", "Jüpiter kadardır"] },
    { s: "Güneş'e en yakın nokta olan Günberi (Perihel) sırasında Dünya'nın Güneş etrafındaki hızı nasıldır?", c: "En yüksek hızına ulaşır", yanlislar: ["En yavaş hızındadır", "Değişmez", "Sıfırlanır"] },
    { s: "Güneş'e en uzak nokta olan Günöte (Aphel) sırasında Dünya'nın Güneş etrafındaki hızı nasıldır?", c: "En yavaş hızına düşer", yanlislar: ["En yüksek hızındadır", "Sabittir", "Maksimuma çıkar"] },
    { s: "Dünya'nın dönme ekseninin uzayda yaklaşık 26.000 yıllık bir periyotla daire çizerek sallanması hareketine ne ad verilir?", c: "Presesyon (Yalpalanma)", yanlislar: ["Nutation", "Aberasyon", "Paralaks"] },
    { s: "Presesyon hareketi sonucunda Dünya'nın gökyüzündeki kutup noktası hangi zamanla değişir?", c: "Binlerce yıl içinde farklı yıldızlara (örneğin Vega'ya) taşınır", yanlislar: ["Hiçbir zaman değişmez", "Her yıl yer değiştirir", "Sadece ayda bir kayar"] },
    { s: "Gökbilimde ışığın kütleçekim alanlarından geçerken bükülmesi olayına ne denir?", c: "Kravitasyonel Mercekleme (Gravitational lensing)", yanlislar: ["Işık kırılması", "Optik yansıma", "Doppler kayması"] },
    { s: "Uzak galaksilerin ışığının kırmızıya kayması (Redshift) neyin doğrudan kanıtıdır?", c: "Evrenin genişliyor olduğunun", yanlislar: ["Galaksilerin küçüldüğünün", "Yıldızların söndüğünün", "Dünya'nın hızlandığının"] },
    { s: "Eğer bir galaksi bize doğru yaklaşıyorsa ışığında gözlemlenen renk kayması hangi yöndedir?", c: "Maviye kayma (Blueshift)", yanlislar: ["Kırmızıya kayma", "Saraya kayma", "Değişmez"] },
    { s: "Güneş'in Samanyolu galaksisi merkezi etrafındaki bir tam turunu tamamlamasına bilim insanları ne ad verir?", c: "Galaktik Yıl (Kozmik Yıl)", yanlislar: ["Güneş yılı", "Işık yılı", "Astronomik döngü"] },
    { s: "Dinozorların soyunun tükenmesine sebep olan dev göktaşının Dünya'ya çarptığı yer neresidir?", c: "Chicxulub Kraterleri (Meksika / Yucatan Yarımadası)", yanlislar: ["Arizona Krateri", "Vredefort Krateri", "Popigai Krateri"] },
    { s: "Dünya'nın en iyi korunmuş büyük meteor kraterlerinden biri olan Barringer Krateri nerededir?", c: "Arizona, ABD", yanlislar: ["Sibirya, Rusya", "Sahra Çölü, Afrika", "Quebec, Kanada"] },
    { s: "Güneş sistemindeki en büyük çarpışma havzalarından biri olan ve Güney Kutup-Aitken Havzası nerede yer alır?", c: "Ay'ın arka yüzünde", yanlislar: ["Mars'ın yüzeyinde", "Merkür'ün ekvatorunda", "Jüpiter'in uydusunda"] },
    { s: "Uzay araçlarının Güneş sistemindeki gezegenleri incelemek için kullandığı 'Flyby' (yakın geçiş) manevrası ne anlama gelir?", c: "Gezegene inmeden veya yörüngesine girmeden yakınından hızla geçerek veri toplamak", yanlislar: ["Gezegene sert iniş yapmak", "Gezegenin etrafında sonsuza kadar dönmek", "Gezegeni bombalamak"] },
    { s: "Uzay ajanslarının Mars'a gönderdiği araçların yüzeye yumuşak iniş yapabilmesi için kullandığı tehlikeli aşamaya genellikle ne ad verilir?", c: "Terörün 7 Dakikası (Seven Minutes of Terror)", yanlislar: ["Kırmızı İniş", "Kritik Frenleme", "Atmosferik Vuruş"] },
    { s: "Mars'ta su arayan ve kaya örneklerini delip tüplerde saklayan son gelişmiş NASA gezgini (rover) hangisidir?", c: "Perseverance", yanlislar: ["Curiosity", "Opportunity", "Spirit"] },
    { s: "Perseverance gezginiyle birlikte Mars atmosferinde uçurulan ilk küçük helikopterin adı nedir?", c: "Ingenuity", yanlislar: ["Sojourner", "Spirit", "Viking"] },
    { s: "Çin'in Mars'a gönderdiği ve başarıyla yüzeye inen ilk keşif aracının adı nedir?", c: "Zhurong", yanlislar: ["Chang'e", "Tianwen", "Yutu"] },
    { s: "Ay'ın karanlık yüzüne (dünyadan görünmeyen tarafına) ilk defa uzay aracı indiren ülke hangisidir?", c: "Çin (Chang'e 4 göreviyle)", yanlislar: ["ABD", "Sovyetler Birliği", "Hindistan"] },
    { s: "Hindistan'ın Ay'ın güney kutbu bölgesine uzay aracı indiren ve başarı sağlayan tarihi görevinin adı nedir?", c: "Chandrayaan-3", yanlislar: ["Mangalyaan", "Gaganyaan", "Aditya-L1"] },
    { s: "Hindistan'ın Güneş'i incelemek üzere fırlattığı ilk uzay gözlem misyonunun adı nedir?", c: "Aditya-L1", yanlislar: ["Surya", "Chandrayaan", "Bhaskara"] },
    { s: "Japonya'nın asteroitlerden toprak örnekleri alıp Dünya'ya getirmeyi başaran ünlü uzay misyonunun adı nedir?", c: "Hayabusa", yanlislar: ["Akatsuki", "Kaguya", "SLIM"] },
    { s: "Avrupa Uzay Ajansı'nın (ESA) kuyruklu yıldız üstüne (67P/Churyumov–Gerasimenko) uzay aracı indiren tarihi misyonunun adı nedir?", c: "Rosetta (Philae modülü ile)", yanlislar: ["Cassini", "Voyager", "New Horizons"] },
    { s: "Satürn sistemini yıllarca inceleyen ve Titan'a Huygens sondasını bırakan ortak NASA/ESA/ASI uzay aracının adı nedir?", c: "Cassini-Huygens", yanlislar: ["Galileo", "Juno", "Dawn"] },
    { s: "Jüpiter'in kutuplarını ve manyetik alanını incelemek için yörüngesinde dönen NASA uzay aracının adı nedir?", c: "Juno", yanlislar: ["Cassini", "Pioneer", "Voyager"] },
    { s: "Plüton ve Kuiper kuşağı cismi Arrokoth'un yakınından geçerek tarihi fotoğraflar çeken NASA uzay aracının adı nedir?", c: "New Horizons (Yeni Ufuklar)", yanlislar: ["New Frontiers", "Deep Space 1", "Pioneer 10"] },
    { s: "Güneş sistemindeki en büyük magmatik ve volkanik kütlelerden biri olan Tharsis Bölgesi hangi gezegendedir?", c: "Mars", yanlislar: ["Venüs", "Dünya", "Merkür"] },
    { s: "Venüs'ün yüzeyinde erimiş kurşunun bile katı kalmasını engelleyecek kadar yüksek olan ortalama sıcaklık kaç derecedir?", c: "Yaklaşık 465 derece", yanlislar: ["100 derece", "1000 derece", "250 derece"] },
    { s: "Merkür'ün yüzeyinde gün ortasında sıcaklık kaç dereceye kadar yükselebilir?", c: "430 derece", yanlislar: ["100 derece", "800 derece", "200 derece"] },
    { s: "Güneş sisteminde kendi etrafında dönme yönü ters olan (retrograd dönen) iki gezegen hangileridir?", c: "Venüs ve Uranüs", yanlislar: ["Merkür ve Mars", "Jüpiter ve Satürn", "Dünya ve Neptün"] },
    { s: "Güneş'e en yakın olan gaz devi gezegen hangisidir?", c: "Jüpiter", yanlislar: ["Satürn", "Uranüs", "Neptün"] },
    { s: "Satürn'ün en büyük uydusu Titan'ın kalın atmosferi temel olarak hangi gazdan oluşur?", c: "Azot (Nitrojen)", yanlislar: ["Oksijen", "Karbondioksit", "Hidrojen"] },
    { s: "Uranüs'ün Güneş etrafındaki bir tam turu (bir yılı) dünyada kaç yıl sürer?", c: "84 yıl", yanlislar: ["12 yıl", "30 yıl", "165 yıl"] },
    { s: "Neptün'ün Güneş etrafındaki bir tam turu (bir yılı) dünyada kaç yıl sürer?", c: "165 yıl", yanlislar: ["84 yıl", "50 yıl", "365 yıl"] },
    { s: "Güneş sistemindeki gezegenlerin yörüngelerinin düzlemi ile Güneş'in ekvator düzlemi arasında küçük bir açı vardır; bu düzleme ne denir?", c: "Tutulum (Ekliptik) düzlemi", yanlislar: ["Galaktik düzlem", "Meridyen çemberi", "Ufuk çizgisi"] },
    { s: "Dünya'nın Güneş etrafındaki yörüngesinin geometrik şekline en yakın biçim nedir?", c: "Hafif basık bir elips", yanlislar: ["Mükemmel daire", "Kare", "Parabol"] },
    { s: "Ay'ın Dünya'ya her döngüsünde bazen devasa görünmesine sebep olan konuma halk arasında ne ad verilir?", c: "Süper Ay", yanlislar: ["Kanlı Ay", "Mavi Ay", "Kara Ay"] },
    { s: "Bir takvim ayı içerisinde iki kez dolunay gerçekleşmesi durumunda ikinci dolunaya ne ad verilir?", c: "Mavi Ay", yanlislar: ["Süper Ay", "Süper Dolunay", "Karanlık Ay"] },
    { s: "Tam Ay tutulması sırasında Ay'ın bakır rengi veya kızıl görünmesinin temel optik sebebi nedir?", c: "Dünya'nın atmosferinden kırılan güneş ışınlarının Ay'ı kırmızı renkte aydınlatması", yanlislar: ["Ay'ın üzerinde yangın çıkması", "Güneş'in kırmızılaşması", "Uzay tozlarının ışığı kesmesi"] },
    { s: "Güneş tutulması sırasında Ay, Güneş'in tamamını örtemeyip etrafında parlak bir halka bırakırsa bu tür tutulmaya ne denir?", c: "Halkalı (Annular) Güneş Tutulması", yanlislar: ["Tam Güneş Tutulması", "Parçalı Güneş Tutulması", "Hibrit Tutulma"] },
    { s: "Yıldızların tayf sınıflaması (O, B, A, F, G, K, M) hangi fiziksel özelliğe göre yapılmıştır?", c: "Yüzey sıcaklığına göre", yanlislar: ["Kütlelerine ve ağırlıklarına göre", "Uzaklıklarına göre", "Yaşlarına göre"] },
    { s: "Güneşimiz tayf sınıflandırmasında hangi harf ile temsil edilen ana kol yıldızıdır?", c: "G sınıfı", yanlislar: ["O sınıfı", "M sınıfı", "A sınıfı"] },
    { s: "Evrendeki en soğuk ve en küçük kütleli ana kol yıldızları hangi tayf sınıfına girer?", c: "M sınıfı (Kırmızı cüceler)", yanlislar: ["O sınıfı", "B sınıfı", "F sınıfı"] },
    { s: "Güneş sistemimize en yakın yıldız sistemi olan Alpha Centauri kaç yıldızdan oluşan bir sistemdir?", c: "3 yıldızdan (Alfa Centauri A, B ve Proxima Centauri)", yanlislar: ["Tek bir yıldızdan", "2 yıldızdan", "4 yıldızdan"] },
    { s: "Geceleri çıplak gözle görülen en parlak yıldız olan Sirius hangi takımyıldızındadır?", c: "Büyük Köpek (Canis Major)", yanlislar: ["Orion", "Küçük Ayı", "Yay"] },
    { s: "Gökyüzünün en büyük kırmızı dev yıldızlarından biri olan ve Orion takımyıldızında yer alan yıldızın adı nedir?", c: "Betelgeuse", yanlislar: ["Rigel", "Sirius", "Vega"] },
    { s: "Orion takımyıldızında yer alan en parlak mavi süperdev yıldızın adı nedir?", c: "Rigel", yanlislar: ["Betelgeuse", "Aldebaran", "Antares"] },
    { s: "Akrep takımyıldızında bulunan ve kırmızı dev olması nedeniyle Betelgeuse'e benzeyen dev yıldızın adı nedir?", c: "Antares", yanlislar: ["Aldebaran", "Arcturus", "Spica"] },
    { s: "Boötes (Çoban) takımyıldızında yer alan gökyüzünün en parlak turuncu dev yıldızlarından birinin adı nedir?", c: "Arcturus", yanlislar: ["Vega", "Capella", "Deneb"] },
    { s: "Lir takımyıldızında bulunan ve gelecekte Dünya'nın kutup yıldızı olacağı bilinen parlak mavi-beyaz yıldız nedir?", c: "Vega", yanlislar: ["Polaris", "Sirius", "Rigel"] },
    { s: "Kuğu takımyıldızının en parlak üyesi olan devasa süperdev yıldızın adı nedir?", c: "Deneb", yanlislar: ["Altair", "Fomalhaut", "Regulus"] },
    { s: "Kartal takımyıldızının en parlak yıldızı olan ve yaz üçgenini oluşturan yıldızlardan biri hangisidir?", c: "Altair", yanlislar: ["Vega", "Deneb", "Sirius"] },
    { s: "Gökyüzünde Vega, Deneb ve Altair yıldızlarının oluşturduğu dev üçgen şekline ne ad verilir?", c: "Yaz Üçgeni", yanlislar: ["Kış Üçgeni", "Büyük Kepçe", "Orion Kemeri"] },
    { s: "Güneş sistemindeki en büyük gaz devi Jüpiter'in kütlesi diğer tüm gezegenlerin toplam kütlesinin yaklaşık kaç katıdır?", c: "İki buçuk katı", yanlislar: ["Yarısı kadar", "Tam eşit", "On katı"] },
    { s: "Satürn'ün öz kütlesi suyun öz kütlesinden ne kadar küçüktür?", c: "Suya atılsa batmayacak kadar (yaklaşık 0.69 g/cm3)", yanlislar: ["Demir kadar ağırdır", "Buzla aynıdır", "Tam sudur"] },
    { s: "Uranüs'ün Güneş etrafında dönerken mevsimlerinin yaklaşık 21 yıl sürmesinin temel sebebi nedir?", c: "Eksen eğikliğinin 98 derece olması nedeniyle yörüngesinde yan yatık dönmesi", yanlislar: ["Çok yavaş dönmesi", "Güneş'e çok uzak olması", "Halkalarının kalın olması"] },
    { s: "Neptün'ün keşfi sırasında matematiksel hesaplamaları bağımsız olarak yapan iki astronom kimlerdir?", c: "Urbain Le Verrier ve John Couch Adams", yanlislar: ["Galileo ve Newton", "Kepler ve Kopernik", "Hubble ve Einstein"] },
    { s: "Plüton'un Uluslararası Astronomi Birliği (IAU) tarafından gezegenlikten çıkarılıp cüce gezegen ilan edildiği yıl hangisidir?", c: "2006", yanlislar: ["1995", "2015", "2000"] },
    { s: "Uluslararası Astronomi Birliği'nin bir gök cismine gezegen denilmesi için koyduğu 3 temel kuraldan biri hangisidir?", c: "Yörüngesini diğer cisimlerden temizlemiş olması", yanlislar: ["Halkasının olması", "Uydusunun bulunması", "Mavi renkte olması"] },
    { s: "Plüton'un gezegen sınıfından düşürülmesinin temel sebebi yukarıdaki 3 kuraldan hangisini sağlayamamasıdır?", c: "Yörüngesindeki diğer Kuiper kuşağı cisimlerini temizleyememiş olması", yanlislar: ["Çok küçük olması", "Güneş'e uzak olması", "Kendi etrafında dönmemesi"] },
    { s: "Evrendeki ilk oluşan elementler Büyük Patlama sonrasında ağırlıklı olarak hangi ikisiydi?", c: "Hidrojen ve Helyum", yanlislar: ["Demir ve Nikel", "Karbon ve Oksijen", "Altın ve Gümüş"] },
    { s: "Yıldızların çekirdeğinde demirden daha ağır elementlerin üretilmesi hangi muazzam olay sırasında gerçekleşir?", c: "Süpernova patlamaları ve Nötron yıldızı çarpışmaları", yanlislar: ["Normal füzyon sırasında", "Kırmızı dev evresinde", "Beyaz cüce soğumasında"] },
    { s: "Evrendeki altın ve platin gibi ağır elementlerin büyük kısmının kaynağı bilim insanlarına göre nedir?", c: "Nötron yıldızlarının çarpışması (kilonova)", yanlislar: ["Güneş patlamaları", "Karadelikler", "Asteroitler"] },
    { s: "İki nötron yıldızının çarpışması sonucu ortaya çıkan ve süpernovadan farklı olarak adlandırılan patlama türü nedir?", c: "Kilonova", yanlislar: ["Hipernova", "Pulsar patlaması", "Gamma ışını demeti"] },
    { s: "Evrendeki en şiddetli enerji patlamaları olan Gama Işını Patlamaları (GRB) genellikle neyin sonucunda oluşur?", c: "Devasa kütleli yıldızların süpernova ile çökmesi veya nötron yıldızı birleşmeleri", yanlislar: ["Güneş lekelerinin patlaması", "Küçük göktaşlarının çarpışması", "Karadeliklerin buharlaşması"] },
    { s: "Stephen Hawking tarafından teorize edilen ve karadeliklerin kuantum etkileriyle yaydığı varsayılan ısıya ne ad verilir?", c: "Hawking Işıması", yanlislar: ["Einstein Radyasyonu", "Kuantum Işıması", "Karadelik Rüzgarı"] },
    { s: "Karadeliğin merkezinde yoğunluğun sonsuz, hacmin sıfır olduğu kabul edilen teorik noktaya ne denir?", c: "Tekillik (Singularity)", yanlislar: ["Olay Ufku", "Merkez Çekirdek", "Çöküş Noktası"] },
    { s: "Kollaps (kütleçekimsel çöküş) yaşayan bir yıldızın ışığın bile kaçamayacağı kadar büzüldüğü sınır yüzeyine ne ad verilir?", c: "Olay Ufku (Event Horizon)", yanlislar: ["Photon Küresi", "Tekillik", "Manyetik Sınır"] },
    { s: "Olay ufkunu geçen ışığın karadelik etrafında halka oluşturduğu bölgeye ne denir?", c: "Foton Küresi (Photon Sphere)", yanlislar: ["Akresyon Diski", "Ergosphere", "Korona"] },
    { s: "Dönen karadeliklerin etrafında uzay-zamanın karadelikle birlikte sürüklendiği dış bölgeye ne ad verilir?", c: "Ergosfer (Ergosphere)", yanlislar: ["Olay Ufku", "Akresyon Diski", "Tekillik"] },
    { s: "Karadeliğin etrafında dönen ve içine düşen maddelerin sürtünmeyle parladığı dönen gaz diskine ne denir?", c: "Akresyon Diski (Yığışma diski)", yanlislar: ["Foton Küresi", "Nebula diski", "Halka sistemi"] },
    { s: "Dünya'dan ilk defa bir karadeliğin (M87 galojisindeki) gölgesinin fotoğrafını yayımlayan uluslararası projenin adı nedir?", c: "Olay Ufku Teleskobu (Event Horizon Telescope - EHT)", yanlislar: ["Hubble Projesi", "James Webb Ağı", "Planck Projesi"] },
    { s: "Samanyolu galaksisinin merkezinde yer alan süper kütleli karadeliğin resmi adı nedir?", c: "Sagittarius A*", yanlislar: ["Cygnus X-1", "M87*", "Centaurus A"] },
    { s: "Keşfedilen ilk karasal aday olan ve X-ışını yayan ünlü karadelik sistemi hangisidir?", c: "Cygnus X-1", yanlislar: ["Sagittarius A*", "V615 Monocerotis", "GRS 1915+105"] },
    { s: "Evrenin en erken dönemlerini ve Büyük Patlama'dan kalan ilk ışığı haritalandıran ESA uzay teleskobunun adı nedir?", c: "Planck Uzay Teleskobu", yanlislar: ["WMAP", "Spitzer", "Chandra X-Ray"] },
    { s: "X-ışını astronomisi yapmak amacıyla uzaya gönderilen ve evrendeki şiddetli olayları inceleyen NASA teleskobu nedir?", c: "Chandra X-ışını Gözlemevi", yanlislar: ["Kepler", "Spitzer", "InSight"] },
    { s: "Kızılötesi uzay gözlemleri yaparak soğuk gaz bulutlarını ve yeni oluşan yıldızları inceleyen teleskobun adı nedir?", c: "Spitzer Uzay Teleskobu", yanlislar: ["Hubble", "Chandra", "Fermi"] },
    { s: "Güneş'in koronasını ve uzay havasını kesintisiz inceleyen NASA'nın güneşe gönderdiği son sondanın adı nedir?", c: "Parker Güneş Sondası", yanlislar: ["SOHO", "STEREO", "Ulysses"] },
    { s: "Güneş ile Dünya arasındaki L1 Lagrange noktasından güneşi izleyen ortak ESA/NASA uzay aracının adı nedir?", c: "SOHO (Solar and Heliospheric Observatory)", yanlislar: ["Parker", "Voyager", "Cassini"] },
    { s: "İki cismin kütleçekim kuvvetleri ile birbirlerine göre hareketsiz kalabildikleri uzaydaki 5 özel denge noktasına ne denir?", c: "Lagrange Noktaları", yanlislar: ["Yörünge Düğümleri", "Manyetik Odaklar", "Kritik Eşikler"] },
    { s: "James Webb Uzay Teleskobu hangi Lagrange noktasında konuşlandırılmıştır?", c: "L2 (İkinci Lagrange Noktası)", yanlislar: ["L1", "L3", "L4"] },
    { s: "L2 Lagrange noktası Dünya'dan yaklaşık ne kadar uzaklıktadır?", c: "1.5 milyon kilometre", yanlislar: ["400 kilometre", "384 bin kilometre", "150 milyon kilometre"] },
    { s: "Lagrange noktalarından L4 ve L5'te biriken asteroitlere ne ad verilir?", c: "Trojan Asteroitleri", yanlislar: ["Kuiper Cisimleri", "Oort Nesneleri", "Apollo Asteroitleri"] },
    { s: "Dünya'nın yörüngesini kesen ve dünyaya çarpma riski taşıyan asteroit grubuna genel olarak ne denir?", c: "NEA (Dünya'ya Yakın Cisimler)", yanlislar: ["Kuiper Cisimleri", "Trojanlar", "Ana Kuşak Cisimleri"] },
    { s: "NASA'nın bir asteroidin yörüngesini kinetik çarpışma yöntemiyle değiştirmeyi başardığı tarihi test misyonunun adı nedir?", c: "DART (Double Asteroid Redirection Test)", yanlislar: ["OSIRIS-REx", "Hayabusa", "Deep Impact"] },
    { s: "NASA'nın Bennu asteroitinden toprak örneği alıp dünyaya başarıyla getiren uzay aracının adı nedir?", c: "OSIRIS-REx", yanlislar: ["DART", "Dawn", "Stardust"] },
    { s: "Cüce gezegen Ceres ve büyük asteroit Vesta'yı ziyaret ederek yörüngelerinde inceleme yapan NASA aracının adı nedir?", c: "Dawn (Şafak)", yanlislar: ["Rosetta", "New Horizons", "Pioneer"] },
    { s: "Jüpiter'in Truva asteroitlerini incelemek üzere fırlatılan uzun soluklu NASA uzay misyonunun adı nedir?", c: "Lucy", yanlislar: ["Dawn", "Juno", "Kepler"] },
    { s: "Güneş sistemindeki en uzak buzlu dev olan Neptün'ün yörüngesinde dönen önde gelen halka yaylarının adları hangi tanrılardan almıştır?", c: "Galle, Le Verrier, Lassell, Arago ve Adams", yanlislar: ["Yunan tanrılarından", "Roma imparatorlarından", "Shakespeare karakterlerinden"] },
    { s: "Uranüs'ün en dışındaki parlak halkasının adı nedir?", c: "Epsilon Halkası", yanlislar: ["Alpha Halkası", "Beta Halkası", "Delta Halkası"] },
    { s: "Satürn'ün en parlak ve geniş iki ana halka tabakası hangileridir?", c: "A ve B Halkaları", yanlislar: ["C ve D Halkaları", "E ve F Halkaları", "G ve H Halkaları"] },
    { s: "Satürn'ün A ve B halkaları arasındaki boşluğa ne ad verilir?", c: "Cassini Boşluğu", yanlislar: ["Encke Yarıkları", "Huygens Aralığı", "Maxwell Bölgesi"] },
    { s: "Güneş sistemindeki gaz ve buz devlerinin halkalarının temel ortak fiziksel özelliği nedir?", c: "Roche sınırının içinde yer almaları", yanlislar: ["Çok sıcak olmaları", "Saf demirden oluşmaları", "Gezegenin manyetik alanını yaratmaları"] },
    { s: "Bir uydunun gezegene çok yaklaşarak gel-git kuvvetleri nedeniyle parçalandığı kritik mesafeye ne denir?", c: "Roche Sınırı", yanlislar: ["Olay Ufku", "Lagrange Sınırı", "Kritik Yörünge"] },
    { s: "Dünya'nın uydusu Ay, gelecekte Roche sınırına kadar yaklaşsaydı ne olurdu?", c: "Gel-git kuvvetleri nedeniyle parçalanıp Dünya'nın etrafında bir halka oluştururdu", yanlislar: ["Güneş'e çarpardı", "Dünya'ya düşerdi", "Yok olup giderdi"] },
    { s: "Yıldızların renk sıcaklığı yasasına göre en soğuk yıldızlar hangi renkte parlar?", c: "Kırmızı", yanlislar: ["Mavi", "Beyaz", "Sarı"] },
    { s: "Güneş'in yüzeyindeki manyetik alan hareketlerinin yarattığı devasa patlamalara ne denir?", c: "Güneş Püskürmesi (Solar Flare)", yanlislar: ["Süpernova", "Kuasar", "Auroral dalga"] },
    { s: "Güneş'in koronasından uzaya fırlatılan milyarlarca tonluk yüklü plazma bulutuna ne ad verilir?", c: "Koronal Kütle Atımı (CME)", yanlislar: ["Güneş Rüzgarı", "Solar Flare", "Manyetik Fırtına"] },
    { s: "Koronal kütle atımları Dünya'nın manyetik alanına çarptığında elektrik şebekelerinde ve uydularda ne yaratabilir?", c: "Jeomanyetik fırtınalar", yanlislar: ["Depremler", "Tsunami", "Ozon tabakası delinmesi"] },
    { s: "Tarihte kaydedilmiş en büyük jeomanyetik fırtına olan ve telegraf hatlarını kilitleyen 1859 yılındaki olay ne olarak bilinir?", c: "Carrington Olayı", yanlislar: ["Tesla Fırtınası", "Güneş Felaketi", "Kutup Fırtınası"] },
    { s: "Gökbilimde yıldızların parlaklığını uzaktakine göre değil mutlak olarak inceleyen Hertzsprung-Russell (H-R) diyagramında Güneş hangi bölgededir?", c: "Ana Kol (Main Sequence)", yanlislar: ["Kırmızı Devler kolu", "Beyaz cüceler bölgesi", "Süperdevler tepesi"] },
    { s: "H-R diyagramının sağ üst köşesinde yer alan yıldız grubu hangisidir?", c: "Kırmızı Devler ve Süperdevler", yanlislar: ["Beyaz Cüceler", "Ana Kol Yıldızları", "Nötron Yıldızları"] },
    { s: "H-R diyagramının sol alt köşesinde yer alan yoğun ve soluk yıldızlar hangileridir?", c: "Beyaz Cüceler", yanlislar: ["Kırmızı Devler", "Protostarlar", "Kuasarlar"] }
];